:doctype: book
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:
// Title Page Variables
:document-type: NASA TECHNICAL HANDBOOK
:document-identifier: NASA-HDBK-XXXX
// document-title:  USE ALL CAPS. If using acronyms in title, check with Sean for approval.  
:document-title: DOCUMENT TITLE
:document-subtitle: TECHNICAL HANDBOOK
////
approved-date: 
 Input the approved date only when publishing.             
 Leave blank until then.  
 Date format: year-month-date
////
:approved-date: 20XX-XX-XX
// document-version: e.g., v1.0,  v1.1, v2.0 etc.
:document-version: vx.x
// document-stage: Input either  "Draft" or "Published"
:document-stage: Draft
// revision-date: remove "//" and input revision date if needed
// :revision-date: 20XX-XX-XX
// comment block out the cover-page-marks before publishing
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
// superseding-document: leave blank if N/A, remove "//" and input doc number if needed
// :superseding-document: NASA-HDBK-2XXX
// :superseding-document-revision: XXXX
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

////
TABLE CONTENTS
 Fill out these fields to complete the table.
 Description of fields:
  application: Application name
  relevanttechnicalstandard:Name of the relevant Technical Standard.  
    i.e. NASA-STD-2601, Section 5.7., NASA document, STIG, NIST, etc.
////

// Document variables
:application:
:relevanttechnicalstandard:

= {application} Handbook

// Do not show the footer for HTML
ifdef::backend-html5[]
:nofooter:
endif::[]

// An additional title is needed for PDF output
ifdef::backend-pdf[]
[colophon]
= {nbsp}
endif::[]

// Title Page
include::document_basecamp/title_page.adoc[]

toc::[]

[dedication]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row!
  Oldest/first version in the bottom row!

  You must add a row to the top of the table each time a new version of the Handbook is published.
 
  Track drafts and include descriptions for each draft while the document is out for review. 

  But be sure to DELETE DRAFT TRACKING and update the approved date when it is signed and ready to be published. 

  The description box must not be left blank, but it should be brief. 
   Example descriptions: "Updated to be applicable to xyz"

NOTE: 
 Approval Date: this will automatically be pulled from the COVER PAGE VARIABLES.

 If you are writing an updated version of a Handbook,  the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Approval Date
|Description

|1.0
|{approved-date}
|
|====

<<<

////

FOREWORD INSTRUCTIONS:
  You must complete the third paragraph by WRITING THE PURPOSE of this handbook. 

  Example: This NASA Technical Handbook provides guidance for configuring Mission systems to be Personal Identity Verification Mandatory (PIV-M) compliant. 

////

== Foreword

This NASA Technical Handbook is published by the National Aeronautics and Space Administration (NASA) as a guidance document to provide engineering information; lessons learned; possible options to address technical issues; classification of similar items, materials, or processes; interpretative direction and techniques; and any other type of guidance information that may help the Government or its contractors in the design, construction, selection, management, support, or operation of systems, products, processes, or services.

This NASA Technical Handbook is approved for use by NASA Headquarters and NASA 
Centers and Facilities. It may also apply to the Jet Propulsion Laboratory (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and 
cooperative agreements, and parties to other agreements only to the extent specified or 
referenced in applicable contracts, grants, or agreements.

This NASA Technical Handbook *(COMPLETE THIS SENTENCE WITH A STATEMENT OF PURPOSE FOR THIS HANDBOOK)*.
//e.g. provides guidance for. . . / establishes best practices for . . .

Requests for information, corrections, or additions to this Handbook can be made via the "Contact ASCS" form, found here: https://cset.nasa.gov/ascs/requests/.

+++<br><br><br><br><br><br><br>+++



////
COMMON CONTENT
  This is the point at which document numbering starts.
  Modification of this section should be fairly common, but not extensive.
  Look for the DOCUMENT CONTENT comment section for the expected place for the body of the work
////

:numbered:

== Scope

CSET handbooks are not requirements documents. Handbooks are produced to provide engineering information; lessons learned; options to address technical issues; and/or classifications of similar items, materials, or processes. Handbooks serve to help ensure that systems are compliant with the requirements defined in CSET’s standards and specifications.

=== Purpose

The purpose of this NASA Technical Handbook is to provide guidance for {application} deployment and operation.

=== Applicability

This NASA Technical Handbook is applicable to technology programs and projects managed by federal employee or contractor Information System Owners (ISOs) at NASA Headquarters and NASA Centers, including Component Facilities and Technical and Service Support Centers. This Handbook applies to the Jet Propulsion Laboratory (JPL), a Federally Funded Research and Development Center (FFRDC), and other non-Agency facility contractors only to the extent specified or referenced in applicable contracts.

CSET's handbooks serve as supplemental guidance and are developed to help ISOs implement the requirements defined in CSET's standards and specifications. NPR 2810.1x, _Security of Information Technology_, clearly defines the role and responsibilities of ISOs in relation to Agency information systems. These responsibilities include:

* Acquiring, developing, integrating, operating, modifying, and maintaining information systems.
* Ensuring system-level implementation of all Agency and Center requirements.
* Taking appropriate actions to identify and minimize or eliminate information system security deficiencies and weaknesses.

Standard guidance will be added, replaced, or removed as appropriate to align these responsibilities with Agency information security- and privacy-related program and project requirements.

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at:

https://standards.nasa.gov/.

== Applicable Documents

=== General
This NASA Technical Handbook provides guidance for configuring systems to be compliant with the requirements defined in the  documents listed in this section.

=== Government Documents

////
ASSOCIATED DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  
  List documents in alphanumerical order based on their Document Number or Descriptor.

  Use YOURLS to link to documents and link the Document Number or Descriptor.


////

[%header, cols=2*a]
|===
|Document Number or Descriptor|Document Title

|NASA-STD-2601|_Security Requirements for Computing Devices_
|NPR 2810.1x|_Security of Information Technology_

|===

=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Number|Document Title

|===

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  The following tables should be in alphabetical order
  Note they do not have a header line, so content can be added in order.
  Add to the tables between the |==== tags
  Example:
    .Definitions                                   <-- table title (will display in presentation)
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Space|Is really, really big                   <-- term and definition/acronym and expansion
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag
////

== Acronyms and Definitions

.Acronyms and Abbreviations
[width="100%",cols="1,3"]
|====
|AO|Authorizing Official
|ACL|Assessed and Cleared List for technology procurement
|ASCS|Agency Security Configuration Standards
|CDM|Continuous Diagnostics and Mitigation
|CIO|Chief Information Officer
|CIS|Center for Internet Security
|CSET|Cybersecurity Standards and Engineering Team
|DAR|Data At Rest
|DISA|Defense Information Systems Agency
|FFRDC|Federally Funded Research and Development Center
|FISMA|Federal Information Security Modernization Act
|FPKI|Federal Public Key Infrastructure
|GRC|Glenn Research Center
|ICAM|Identity, Credential, and Access Management
|IDI|ICAM Device Integration
|ISO|Information System Owner
|JPL|Jet Propulsion Laboratory
|NASA|National Aeronautics and Space Administration
|NCTR|NASA Client Trust Reference
|NIST|National Institute of Standards and Technology
|NPR|NASA Procedural Requirement
|NSA|National Security Agency
|NTAM|NASA Trust Anchor Management
|NTSP|NASA Technical Standards Panel
|OCIO|Office of the Chief Information Officer
|PIV|Personal Identity Verification
|PKI|Public Key Infrastructure
|RISCS|Risk Information and Security Compliance System
|SAISO|Senior Agency Information Security Officer
|SOC|Security Operations Center
|STIG|Security Technical Implementation Guide

|====

.Definitions
[width="100%",cols="1,3"]
|====
||

|====

////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4.
  Each section beyond this (notated by ==) will increment.

NOTE ON INTERNAL CROSS REFERENCE:
  when using internal cross references use the internal function
  instead of keeping track of the sections. The cross reference uses
  <<_ (corner bracket, corner bracket, underscore)
  then lowercase title with any non-alpha as a single underscore)
  then close 2 corner brackets.
  Example:
    ==== Example of a sub-section Title
  Cross Reference:
    <<_example_of_a_sub_section_title>>
  Will Appear as link in published document with subsection number:
    i.e. "6.4.2. Example of a sub-section Title"
////

== DOCUMENT BODY WHICH STARTS AT SECTION 4

Content


////
APPENDIX SECTION

  Appendix number differently then the document, so make sure to use 3 or more morkers on subsection

    titles (=== SUBSECTION). If you drop to 2 markers (==) it will start normal numbering again.
  Content of the appendix will format for sections and subsection, but not number them.
  It is appropriate to continue using heading tags (===) as normal.

  Appendix will be lettered based on the [appendix] tag, so the example title will appear as

  APPENDIX A: TITLE OF APPENDIX


  Additional appendix can be used by the [appendix] tag immediately followed on the next line with a
    2 marker title (== APPENDIX TITLE). following appendix will use appropriate letters (B, C, D...)

////

[appendix]
== TITLE OF APPENDIX
