:doctype: book
ifdef::backend-pdf[]
:front-cover-image: image::build/hdbk-pdf-cover.pdf[]
endif::[]
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
ifdef::backend-html5[]
:toc: macro
:toc-placement!:
endif::[]
:toc-title: TABLE OF CONTENTS
:toclevels: 3
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

// NOTE: include statement need blank line before and after

include::hdbk-document-variables.adoc[]

////
DOCUMENT VARIABLES (that are not on cover page) DESCRIPTIONS:
  topic:  Define the topic of this handbook. This can be an application name, if applicable to your handbook or the name of your solution 
             *example topic values*: Mission PIV-M, PIV SSSD, macOS Smartcard 
  relevanttechnicalstandard:   Name of the relevant Technical Standard. (i.e. NASA-STD-2601, Section 5.7., NASA document, STIG, NIST, etc.)
////

// Document variables (that are not on cover page)
:topic:
:relevanttechnicalstandard:

:noheader:
:nofooter:

ifdef::backend-pdf[]
= {topic} Handbook
{document-subtitle}
:toc: preamble
endif::[]

ifdef::backend-html5[]
= {topic} Handbook

// NOTE: include statement need blank line before and after

include::document_basecamp/title_page.adoc[]

toc::[]

endif::[]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row! 
  Oldest/first version in the bottom row!

  You must *add a row to the top of the table* each time a new version of the Handbook is published.
 
  Track drafts and include descriptions for each draft while the document is out for review. 

  But be sure to DELETE DRAFT TRACKING and update the published date when it is ready to be published. 

  The description box must not be left blank, but it should be brief. 
   Example descriptions: "Updated to be applicable to xyz"

   NOTE: 
    published-date: this will automatically be pulled from the document-variables.adoc file.

    If you are writing an updated version of a Handbook, the published date must be hard coded for the earlier version(s), and the published-date variable must be used only for the most recent version.
////

[dedication]
== Document History Log
ifdef::backend-pdf[]
:!nofooter:
:!noheader:
endif::[]

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Published Date
|Description

|1.0
|{published-date}
|
|====

<<<

////
FOREWORD INSTRUCTIONS:
  --> Paragraph 3 of Foreword.
      *You must write in THE PURPOSE* of this handbook to complete the sentence that begins with "This NASA Technical Handbook"

        *Example* (from NASA-HBK-2670, Mission PIV-M):  
            This NASA Technical Handbook provides guidance for configuring Mission systems to be Personal Identity Verification Mandatory (PIV-M) compliant. 
////

== Foreword

This NASA Technical Handbook is published by the National Aeronautics and Space Administration (NASA) as a guidance document to provide engineering information; lessons learned; possible options to address technical issues; classification of similar items, materials, or processes; interpretative direction and techniques; and any other type of guidance information that may help the Government or its contractors in the design, construction, selection, management, support, or operation of systems, products, processes, or services.

This NASA Technical Handbook is approved for use by NASA Headquarters and NASA Centers and Facilities. It also applies to the Jet Propulsion Laboratory (JPL) (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

This NASA Technical Handbook *(COMPLETE THIS SENTENCE WITH A STATEMENT OF PURPOSE FOR THIS HANDBOOK)*.
// provides guidance for {topic} deployment and operation.
// provides guidance for. . . 
// establishes best practices for configuring {topic}. . .

Requests for information, corrections, or additions to this Handbook can be made via the "Contact ASCS" form, found here: https://cset.nasa.gov/ascs/requests/.

+++<br><br><br><br><br><br><br>+++



////
COMMON CONTENT
  This is the point at which document numbering starts.
  Modification of this section should be fairly common, but not extensive.
  Look for the DOCUMENT CONTENT comment section for the expected place for the body of the work
////

:numbered:

== Scope

This Handbook is not a requirements document. The Cybersecurity Standards and Engineering Team (CSET) creates handbooks to provide engineering information; lessons learned; options to address technical issues; and/or classifications of similar items, materials, or processes. Handbooks serve to help ensure that systems are compliant with the requirements defined in CSET’s standards and specifications.

////
PURPOSE: 
  Make sure to complete the sentence AND provide more supporting details (if necessary) to describe why this handbook is necessary

   *Example* (from NASA-HBK-2670, Mission PIV-M):  
    The purpose of this NASA Technical Handbook is to provide guidance for configuring Mission systems to be PIV-M compliant. 

    Homeland Security Presidential Directive-12 (HSPD-12), the Federal Information Security Modernization Act (FISMA), and other Federal directives and standards require NASA systems to use PIV-based authentication for physical and logical access (i.e., to be PIV-M compliant). 
    
    The solution laid out in this handbook was developed by the Cybersecurity Services and Integration Division (Code 710) System Administrator team in order to allow systems used on networks that are isolated from NASA’s Corporate infrastructure (e.g., Mission systems) to be PIV-M compliant.

    This Handbook provides the configurations necessary for Information System Owners (ISOs) of systems in isolated AD environments to carry out authentication and user management via their own local AD while also enabling these systems to be PIV-M compliant.   
////

=== Purpose

The purpose of this NASA Technical Handbook is to *(COMPLETE THIS SECTION BY EXPLAINING THE PURPOSE OF THIS HANDBOOK)*.

// provide guidance for {topic} deployment and operation.
// provide guidance for configuring {topic}. 
// provide a solution for . . .
// establish best practices for configuring . . .

=== Applicability

This NASA Technical Handbook is approved for use by NASA Headquarters and NASA Centers and Facilities. It also applies to the Jet Propulsion Laboratory (JPL), a Federally Funded Research and Development Center (FFRDC), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in their applicable contracts, grants, or agreements.


=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized CSET, via the Agency Security Configuration Standards (ASCS) initiative, to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at: https://standards.nasa.gov/.

CSET's handbooks serve as supplemental guidance and are developed to provide assistance in the implementation of requirements defined in CSET's standards and specifications. CSET authorizes the process(es), tool(s), mechanism(s), and/or configuration(s) provided in this Handbook as an approved means of meeting the associated requirements defined in the documents listed in Section 2., _Applicable Documents_. 

////
APPLICABLE DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  
  List documents in alphanumeric order based on their Document Number or Descriptor.

  Use YOURLS to link to documents and link the Document Number or Descriptor.
////

== Applicable Documents

This NASA Technical Handbook provides guidance for configuring systems to be compliant with the requirements defined in the documents listed in this section.

NOTE: A suffix of __x__ on a document identifier indicates that the latest issuance of the document applies.

=== Government Documents

.White House Releases
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===

.NASA Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
|link:https://cset.nasa.gov/latest/nasa-std-2601[NASA-STD-2601]| _Minimum Cybersecurity Requirements for Computing Systems_ 
|link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1__x__]| _Security of Information Technology_
| | 
|===

.NIST Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===

.Other Government Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===

// NOTE: Comment out the Non-Government Documents table if you do not have any documents to include.  (i.e., Do not leave a blank table in the document)

=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  Add and remove acronyms as needed. 
  List acronyms, abbreviations, and definitions in alphabetical order.

  Change the title of this section as necessary: 
    If you don't have anything for the Definitions table, delete the table and change Section 3 title to: == Acronyms and Abbreviations
////

== Acronyms, Abbreviations, and Definitions

include::acronymlist.adoc[] 

// If you don't have anything for the Definitions table, delete the table and change Section 3 title to: == Acronyms and Abbreviations

.Definitions
[width="100%",cols="1,3"]
|====
| |

|====

////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4.

NOTE ON INTERNAL CROSS REFERENCE:
  when using internal cross references use the internal function
  instead of keeping track of the sections. The cross reference uses
  <<_ (corner bracket, corner bracket, underscore)
  then lowercase title with any non-alpha as a single underscore)
  then close 2 corner brackets.
  Example:
    ==== Example of a sub-section Title
  Cross Reference:
    <<_example_of_a_sub_section_title>>
  Will Appear as link in published document with subsection number:
    i.e. "6.4.2. Example of a sub-section Title"
////

////
PREREQUISITES: 
  Clearly define anything that is required for someone to implement the steps in this handbook.

  *Example* (from NASA-HBK-2670, Mission PIV-M):  
    The following requirements must be met on a server for this solution to be viable:
      1. The server must be running Windows Server 2016 or Windows Server 2019.
      2. The AD Domain Services (AD DS) role must be installed.
      3. The user configuring the PIV-M solution must have an AD user account with Domain Admin rights.

       * Domain Admin rights are required to add the sshPublicKeys attribute and to execute general AD configurations.

////

== Prerequisites

The following requirements must be met for this solution to be viable:

. 
. 

////
CAVEATS: 
  Clearly define any caveats for the solution/process defined in this handbook. 
  Delete or comment out this section if N/A. 

 *Example* (from NASA-HBK-2670, Mission PIV-M):  
   The following caveats should be carefully reviewed before implementing this solution:
      1. For full compliance, this solution requires the use of either the Mission PIV Certificate Revocation List (CRL),which can be found here: Mission PIV CRL Solution, or your own CRL validation solution.
      2. The registry settings to disable CRL validation for testing need to be removed to be PIV-M compliant.
      3. The solution provided in this Handbook contains configurations that specifically call out Mission systems and settings.

////

== Caveats

The following caveats should be carefully reviewed before implementing this solution:

. 
. 

////
PROCESS/STEP: 
  At this point, begin walking through the process/solution defined in this handbook.

  *Important*: Authors need to title this section with the step or process (do not leave "Process/Step" as this section title.) 

  Add sections and subsections as needed to identify different steps in implementing the process/solution. 

  *Example* (excerpts from NASA-HBK-2670, Mission PIV): 
   6. CONFIGURING PIV-M SOLUTION FOR LINUX 
   7. CONFIGURING PIV-M SOLUTION FOR WINDOWS
      6.1. Domain-Join Windows Clients to Mission Active Directory
      6.2. Scope PIV-M MBE GPO to Applicable Endpoints
////

== Process/Step 



////
APPENDIX SECTION

  Appendices are identified differently then the rest of the document, so make sure to use 3 or more markers on subsection titles (=== SUBSECTION).
  
  If you drop to 2 markers (==) it will start normal numbering again.

  Content of the appendix will format for sections and subsection, but not number them.
  
  It is appropriate to continue using heading tags (===) as normal.
  
  Appendices will be lettered based on the [appendix] tag, so the example title will appear as: 
     APPENDIX A: TITLE OF APPENDIX

  Additional appendices can be used by the [appendix] tag immediately followed on the next line with a 2 marker title (== APPENDIX TITLE).
  
  Subsequent appendices will use appropriate letters (B, C, D...)
////

[appendix]
== TITLE OF APPENDIX
