:doctype: book
// Document Setup
// HTML
:stylesdir: document_basecamp/
//:stylesheet: asciidoctor-draft.css
:stylesheet: asciidoctor.css
// PDF
:pdf-fontsdir: document_basecamp/fonts/
:pdf-themesdir: document_basecamp/
//:pdf-theme: asciidoctor-pdf-draft.yml
:pdf-theme: asciidoctor-pdf.yml
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
:chapter-signifier:
// Table of Contents
:toc: macro
:toc-placement!:
:toc-title: TABLE OF CONTENTS
:toclevels: 3
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

// Title Page Variables
:document-type: NASA TECHNICAL HANDBOOK
:document-identifier: NASA-HDBK-XXXX
// document-title:  USE ALL CAPS. If using acronyms in title, check with Sean for approval.  
:document-title: DOCUMENT TITLE
:document-subtitle: TECHNICAL HANDBOOK
////
published-date: 
 Input the date only when publishing.             
 Leave blank until then.  
 Date format: year-month-date: 20XX-XX-XX 
////
:published-date: 
// document-version: e.g., v1.0,  v1.1, v2.0 etc.
:document-version: vx.x
// is-draft: Is this document a draft? (enter true if it is a draft)
:is-draft: True
// document-stage: Input "Draft", "Informal Draft", or "Formal Draft"
:draft-stage: Draft
// revision-date: remove "//" from line below and input revision date if needed
// :revision-date: 20XX-XX-XX
// delete values for the cover-page-marks and leave blank before publishing - do not comment out or build script will break
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
// superseding-document: leave commented out if N/A, remove "//" on lines below and input doc number if needed
// :superseding-document: NASA-HDBK-2XXX
// :superseding-document-version: vx.x

// Customize document header
ifeval::["{is-draft}" == "True"]
:document-header: {document-identifier} {document-version} {draft-stage}
endif::[]
ifeval::["{is-draft}" != "True"]
:document-header: {document-identifier} {document-version}
endif::[]

////
*DOCUMENT VARIABLES (that are not on the title page) DESCRIPTIONS:*
  topic: Define the topic of this handbook. This can be an application name, if applicable to your handbook or the name of your solution 
    - example topic values: Mission PIV-M, PIV SSSD, macOS Smartcard 

  relevanttechnicalstandard: Name of the relevant Technical Standard 
    - examples: NASA-STD-2601, NPR 2810.1__x__; NIST SP 800-53 Rev. 5
////

// DOCUMENT VARIABLES (that are not on cover page):
:topic:
:relevanttechnicalstandard:

:noheader:
:nofooter:


= {topic} Handbook

// NOTE: include statement need blank line before and after

include::document_basecamp/title_page.adoc[]

toc::[]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row
  Oldest/first version in the bottom row

  You must *add a row to the top of the table* each time a new version of the Handbook is published.

  The description box must not be left blank, but it should be brief. 
   Example description: Updates made per EO 14028, _Executive Order on Improving the Nation’s Cybersecurity_; general language cleanup; reformatted using current ASCS template.

  published-date: this will automatically be pulled from the document-variables.adoc file.

  If you are writing an updated version of a Handbook, the published date must be hard coded for the earlier version(s), and the published-date variable must be used only for the most recent version.
////

[dedication]
== Document History Log

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Published Date
|Description

|
|{published-date}
|
|====

<<<


== Foreword

This NASA Technical Handbook is published by the National Aeronautics and Space Administration (NASA) as a guidance document to provide engineering information; lessons learned; possible options to address technical issues; classification of similar items, materials, or processes; interpretative direction and techniques; and any other type of guidance information that may help the Government or its contractors in the design, construction, selection, management, support, or operation of systems, products, processes, or services.

This NASA Technical Handbook is approved for use by NASA Headquarters and NASA Centers and Facilities. It also applies to the Jet Propulsion Laboratory (JPL) (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

Requests for information, corrections, and/or additions to this Handbook can be made via the link:https://cset.nasa.gov/latest/contact-ascs[Contact ASCS] form.

+++<br><br><br>+++



// This is the point at which document numbering starts.

:numbered:

== Scope

This Handbook is not a requirements document. Agency Security Configuration Standards (ASCS) handbooks are created to provide engineering information; lessons learned; options to address technical issues; and/or classifications of similar items, materials, or processes. Handbooks serve to help ensure that systems are compliant with the requirements defined in ASCS standards and specifications.

////
*PURPOSE:*
  Make sure to complete the sentence AND provide more supporting details (if necessary) to describe why this handbook is necessary

   *Example* (from NASA-HBK-2670, Mission PIV-M):  
    The purpose of this NASA Technical Handbook is to provide guidance for configuring Mission systems to be PIV-M compliant. 

    Homeland Security Presidential Directive-12 (HSPD-12), the Federal Information Security Modernization Act (FISMA), and other Federal directives and standards require NASA systems to use PIV-based authentication for physical and logical access (i.e., to be PIV-M compliant). 
    
    The solution laid out in this handbook was developed by the Cybersecurity Services and Integration Division (Code 710) System Administrator team in order to allow systems used on networks that are isolated from NASA’s Corporate infrastructure (e.g., Mission systems) to be PIV-M compliant.

    This Handbook provides the configurations necessary for Information System Owners (ISOs) of systems in isolated AD environments to carry out authentication and user management via their own local AD while also enabling these systems to be PIV-M compliant.   
////

=== Purpose

The purpose of this NASA Technical Handbook is to *COMPLETE THIS SECTION BY EXPLAINING THE PURPOSE OF THIS HANDBOOK*.

// provide guidance for {topic} deployment and operation.
// provide guidance for configuring {topic}. 
// provide a solution for . . .
// establish best practices for configuring . . .

=== Applicability

This NASA Technical Handbook is approved for use by NASA Headquarters and NASA Centers and Facilities. It also applies to JPL, other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in their applicable contracts, grants, or agreements.

This NASA Technical Handbook is applicable to *COMPLETE THIS SECTION BY EXPLAINING THE APPLICABILITY OF THIS HANDBOOK*.

// macOS systems.
// Infrastructure as a Service (Iaas) cloud computing systems.
// Windows 11 operating systems.

<<<<
  
=== Authority

The NASA Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized CSET, via the Agency Security Configuration Standards (ASCS) initiative, to create binding Technical Standards related to cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within NASA.

ASCS handbooks serve as supplemental guidance and are developed to provide assistance in the implementation of requirements defined in ASCS standards and specifications. ASCS authorizes the process(es), tool(s), mechanism(s), and/or configuration(s) provided in this Handbook as an approved means of meeting the associated requirements defined in the documents listed in <<Requirements Documents>>.


////
APPLICABLE DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  
  List documents in alphanumeric order based on their Document Number or Descriptor.

  Use YOURLS to link to documents and link the Document Number or Descriptor.
////

== Applicable Documents

=== Requirements Documents

This NASA Technical Handbook provides guidance for configuring systems to be compliant with the requirements defined in the documents listed in this section.

NOTE: A suffix of __x__ on a document identifier indicates that the latest issuance of the document applies.

==== Government Documents

// NOTE: based on your document's specific needs, make visible any of the document tables that are commented out below: 

////
.White House Releases
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////

.National Aeronautics and Space Administration (NASA) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
|link:https://cset.nasa.gov/latest/nasa-std-2601[NASA-STD-2601]| _Minimum Cybersecurity Requirements for Computing Systems_ 
|link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1__x__]| _Security of Information Technology_
// | | 
|===


////
.Defense Information Systems Agency (DISA) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////
.National Institute of Standards and Technology (NIST) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////

// Create YOURLS for any other Government documents. Link the title of the source in the table below. 

.Other Government Documents
[%header]
|===
|Document Title
| 
|===
////

////
==== Non-Government Documents

// Create YOURLS for any non-Government documents. Link the title of the source in the table below. 

[%header]
|===
|Document Title
| 
|===
////


////
SUPPLEMENTAL GUIDANCE: 
Add any websites, handbooks, etc. that you used as a reference while writing this Handbook.
 - List documents in alphabetical order based on the title.
 - *Use YOURLS* to link to documents and *link the title of the document*.
////

=== Supplemental Guidance

The resources listed in this section were used as a reference while writing this NASA Technical Handbook and may serve as additional support in implementing the solution defined in this Handbook.


[%header]
|===
|Title
| 
| 
|===



+++<br>+++

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  Change the title of this section as necessary: 
    If you don't have anything for the Definitions table, comment out the definitions table and change Section 3 heading to: == Acronyms and Abbreviations
////

== Acronyms, Abbreviations, and Definitions

include::acronym_list.adoc[] 

<<<

include::definitions.adoc[]

<<<


////
DOCUMENT CONTENT
  At this point, the body of the document starts.
  Numbering should be at section 4.
////


////
PREREQUISITES: 
  Clearly define anything that is required for someone to implement the steps in this handbook.

  *Example* (from NASA-HBK-2670, Mission PIV-M):  
    The following requirements must be met on a server for this solution to be viable:
      1. The server must be running Windows Server 2016 or Windows Server 2019.
      2. The Active Directory Domain Services (AD DS) role must be installed.
      3. The user configuring the PIV-M solution must have an AD user account with Domain Admin rights.

       * Domain Admin rights are required to add the sshPublicKeys attribute and to execute general AD configurations.

////

== Prerequisites

The following requirements must be met for this solution to be viable:

. _xyz_
. _xyz_

////
CAVEATS: 
  Clearly define any caveats for the solution/process defined in this handbook. 
  Delete or comment out this section if N/A. 

 *Example* (from NASA-HBK-2670, Mission PIV-M):  
   The following caveats should be carefully reviewed before implementing this solution:
      1. For full compliance, this solution requires the use of either the Mission PIV Certificate Revocation List (CRL),which can be found here: Mission PIV CRL Solution, or your own CRL validation solution.
      2. The registry settings to disable CRL validation for testing need to be removed to be PIV-M compliant.
      3. The solution provided in this Handbook contains configurations that specifically call out Mission systems and settings.

////

== Caveats

The following caveats should be carefully reviewed before implementing this solution:

. _xyz_
. _xyz_

////
Begin Instructions: 
  At this point, begin walking through the process/solution defined in this handbook.

  *Important*: Authors need to title this section with the step or process 
   Add sections and subsections as needed to identify different steps in implementing the process/solution. 

  *Example* (excerpts from NASA-HBK-2670, Mission PIV): 
   6. CONFIGURING PIV-M SOLUTION FOR LINUX 
   7. CONFIGURING PIV-M SOLUTION FOR WINDOWS
      6.1. Domain-Join Windows Clients to Mission Active Directory
      6.2. Scope PIV-M MBE GPO to Applicable Endpoints
////

== Begin Instructions 


+++<br>+++

////
APPENDIX SECTION

Appendices will be lettered (not numbered). 

Appendices can be added by putting the marker [appendix] on one line, and then, directly underneath (on the next line), write the 2 marker title in all caps for the appendix.
  Example: 
    [appendix]
    == Title of Appendix 

  Example title will appear as:
   APPENDIX A: Title of Appendix 

////

////

[appendix]
== Title of Appendix 

////
