include::hdbk-document-variables.adoc[]


= {document-identifier}, _{document-title}_

:numbered:

== DESCRIPTION
This NASA Technical Handbook *(COMPLETE THIS SENTENCE WITH A STATEMENT OF PURPOSE FOR THIS HANDBOOK)*.

NOTE: Comments, concerns, issues found in the content of this Handbook can be directed to NASA-DL-ASCS-TECHNICAL@mail.nasa.gov

or this: 

NOTE: Requests for information, corrections, or additions to this Handbook can be made via the "Contact ASCS" form, found here: https://cset.nasa.gov/ascs/requests/.

== HANDBOOK

// Edit the link below: 

HTML and PDF documents will be maintained within https://developer.nasa.gov/ASCS/INSERTLINK[GitHub Releases].



== DOCUMENT HISTORY

// Highlights = Include current version and last version 
// Only include big important changes in the description

.Highlights from Document History 
[%header,width="100%",cols="1,1,3"]
|====
|Document Version
|Published Date
|Description

|{document-version}
|{published-date}
|

| *TYPE IN PREVIOUS VERSION*
| *TYPE IN PREVIOUS DATE APPROVED*
|
|====

// Edit the link below: 

NOTE: For a complete, detailed history of changes made to this document, see the link:CHANGELOG.adoc[Full Changelog]. 
