= Document Basecamp

This repository houses the AsciiDoc templates and styles utilized to create CSET's Standards, Handbook, Specifications.

== Templates
The following subsections provide directions on where to find each of CSET's document template directories, the contents of those directories, and instructions on how to use the files contained in those directories. 

The files contained in each of these directories serve as the format to be used for creating each kind of CSET document. 

=== CSET Handbooks
CSET's Handbook template directory is located in the following location: https://developer.nasa.gov/CSET/document_basecamp/tree/master/hdbk

*This directory contains the following three files:*

* handbook.adoc
* hbk-pdf-cover.adoc
* hdbk-document-variables.adoc

*When creating or updating a Handbook* you will need to clone this entire directory (see the section titled _Git Workflow_ below to make sure you have done this correctly).
When you are ready to write or update your Handbook, follow these steps: 

. Input or edit the variables in the *hdbk-document-variables.adoc* file first. The variables in this document will be used throughout the guide and the cover page. 
. Then write or update the *handbook.adoc* file - this is where the main contents of your Handbook will be contained. 

*Note:*  You do not need to edit the *hbk-pdf-cover.adoc* file, but this file does need to be included for the pdf version of your Handbook to be properly generated. 


=== CSET Specifications
CSET's Specification template directory is located in the following location: https://developer.nasa.gov/CSET/document_basecamp/tree/master/scs

*This directory contains the following three files:*

* spec-document-variables.adoc
* spec-pdf-cover.adoc
* specification-simple.adoc
* specification.adoc

*When creating or updating a Specification* you will need to clone this entire directory (see the section titled _Git Workflow_ below to make sure you have done this correctly).
When you are ready to write or update your Spec, follow these steps: 

. Input or edit the variables in the *spec-document-variables.adoc* file first. The variables in this document will be used throughout the guide and the cover page. 
. Then write or update the *specification.adoc* file - this is where the main contents of your Spec will be contained. 
.. Use the *specification-simple.adoc* file instead of the specification.adoc file for Simple Specifications. 

*Note:*  You do not need to edit the *spec-pdf-cover.adoc* file, but this file does need to be included for the pdf version of your Spec to be properly generated. 


=== CSET Standards
CSET's Standards template directory is located in the following location: https://developer.nasa.gov/CSET/document_basecamp/tree/master/std

*This directory contains the following three files:*

* standard.adoc
* std-document-variables.adoc
* std-pdf-cover.adoc

*When creating or updating a Standard* you will need to clone this entire directory (see the section titled _Git Workflow_ below to make sure you have done this correctly).
When you are ready to write or update your Standard, follow these steps: 

. Input or edit the variables in the *std-document-variables.adoc* file first. The variables in this document will be used throughout the guide and the cover page. 
. Then write or update the *standard.adoc* file - this is where the main contents of your Standard will be contained. 

*Note:*  You do not need to edit the *std-pdf-cover.adoc* file, but this file does need to be included for the pdf version of your Spec to be properly generated. 

== Git workflow

=== New Repository 

TODO: link or document the developer.nasa.gov side of making a new repository

=== First Clone

Cloning a local copy of your working repository can be done via GUI or via shell commands. 

TODO: link to GUI 

.Command Line Cloning
[source]
----
git clone <name of repo>
----

=== First Branch

Since the repository clone will place you in the master branch the first action will be to make a new branch to work in.

.Command Line Branch
[source]
----
cd <name of repo>
git branch <new branch name>
git checkout <new branch name>
----

=== Git Submodule 

After cloning and in a new branch you can link the common templates and tools with the repository.

Adding the Document Basecamp to a document tree uses the git submodule command. The document_basecamp directory will be added as a submodule in the repository. 

.Command Line Submodule
[source]
----
git submodule add https://developer.nasa.gov/CSET/document_basecamp.git
git add .
git commit -m "adding document_basecamp to document"
git push origin <branch name>
----

=== Document Header

All asciidoc documents will need to have a header added in order to publish with the proper presentation settings provided by the document_basecamp. A helper script is provided in the document_basecamp that will generate this base and add an entry into the README file associated to the document repository. 

Manually adding the header to a document is valid as well, a new document should be created and the following header added to it. 

.Document header example
[source]
----
= <the title of your document>
:doctype: article
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:
----

It is good practice to add a link into the README file of the repository since the README file is the landing page for the document repository. 

.README file link example
[source]
----
link:<the name of your asciidocfile>.adoc[]
----

=== First Push

Now that you have a new repository, a branch to work in, the basecamp set up, and some simple file stubs, you should push the branch up to the server regularly while you are working on it. 

.Command Line Branch Push
[source]
----
git add .
git commit -m "<make a comment about what the changes are>"
git push origin <branch name>
----

=== Continued Maintenance

Cloning or fetching the document_basecamp from a previous commit, this is done in the root of the document. Before you run these commands you should see a .gitmodule file (hidden) and a document_basecamp directory that is empty. 

[source]
----
git submodule init
git submodule update
----

Updating a submodule

[source]
----
cd document_basecamp
git fetch
git merge -s recursive -Xours origin origin/master
----

== Asciidoctor 

In most cases generation of the published version of the files are done via commands on the command line, if you are using a GUI tool the should be an option to open in Shell (Windows) or Terminal (Mac). 

=== Generating HTML

[source]
----
asciidoctor -a allow-data-uri <name of doc>.adoc
----

=== Generating PDF

[source]
----
asciidoctor-pdf -r ./document_basecamp/scripts/asciidoctor-pdf-extensions.rb <name of doc>.adoc
----

== Platform Specific Notes

=== Linux Setup

In order to get asciidoctor and asciidoctor-pdf working on RHEL 7 Workstations the following configurations should be made. 

Using rbenv (https://github.com/rbenv/rbenv)[https://github.com/rbenv/rbenv] allows us to have multiple version of Ruby since the stock version in RHEL 7 does not support asciidoctor-pdf. 

[source]
----
mkdir ~/opensource
cd ~/opensource
git clone https://github.com/rbenv/rbenv.git
ln -s opensource/rbenv .rbenv
export PATH=$PATH:/home/jtgilber/.rbenv/bin
mkdir -p "$(rbenv root)"/plugins
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
sudo yum install openssl-devel readline-devel zlib-devel
eval "$(rbenv init -)"
rbenv install 2.5.1
rbenv global 2.5.1
rbenv local 2.5.1
gem install asciidoctor
gem install asciidoctor-pdf
gem install pygments.rb
gem install coderay
----

