

= Document Basecamp

This repository houses the AsciiDoc templates used to create CSET's standards, handbooks, and specifications. 

This README provides instructions on where to find each of CSET's document template directories, the contents of those directories, and how to use the files contained in those directories. 

TIP: See <<_using_github, Section 4. __Using GitHub__>> for supplemental guidance. 

+++<br>+++

'''

:numbered:

== CSET Handbooks

NOTE: CSET's Handbook template directory is located here: https://developer.nasa.gov/CSET/document_basecamp/tree/master/hdbk

=== Using the CSET Handbook Template

1. Open your Handbook in Visual Studio Code (VSC).

2. Add Document Basecamp as a submodule within your Handbook.
** See <<_how_to_add_the_document_basecamp_submodule, Section 4.2. __How to Add the Document Basecamp Submodule__>> for instructions.

3. Copy the following files from Document Basecamp and paste them into your Handbook's root directory: 

 * From the *hdbk folder* in Document Basecamp:

  . handbook.adoc
  . hdbk-document-variables.adoc 
  . hbk-pdf-cover.adoc
  . README.adoc

 *  From Document Basecamp:

  . acronym_list.adoc
  . definitions.adoc

WARNING: Do not rename these files. Files reference each other by name.

[start=4]
4. Input or edit the variables in your Handbook's copy of the *hdbk-document-variables.adoc* file first. 
 ** The variables in this file will be used throughout the Handbook and the cover page. 

5. Next, write or update your Handbook's copy of the *handbook.adoc* file - this is where the main contents of your Handbook will be contained. 

6.  Update your Handbook's copy of the *definitions.adoc* file to include the terms used throughout your Handbook. 
 ** Note that you may add terms to your copy of the definitions.adoc file if necessary. 
 *** You may want to use this language: "For the purposes of this Handbook, <xyz term> is used to refer to <fill in your handbook-specific definition>."

7. Update your Handbook's copy of the *acronym_list.adoc* to include the acronyms used throughout your Handbook. 
 ** Note: ISO, RBD, and SSP are in the template acronym list because they appear in the spec and std templates - if you do not use these acronyms in your own document's content, make sure to comment them out of the acronym_list.adoc file. 

8. Update your Handbook's copy of the *README.adoc*. 
 ** Note that there is a template for you to fill in. The README template was added in Spring 2022 to improve uniformity across CSET's documents.  

IMPORTANT: You will not edit the *hbk-pdf-cover.adoc* file, but this file does need to be copied over from document_basecamp and pasted into your document's root directory for the pdf version of your Handbook to be properly generated. 

=== Generating HTML Handbooks

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor -D build handbook.adoc
----

=== Generating PDF Handbooks

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor-pdf -D build hdbk-pdf-cover.adoc handbook.adoc
----

+++<br>+++

== CSET Specifications

NOTE: CSET's Specification template directory is located here: https://developer.nasa.gov/CSET/document_basecamp/tree/master/spec

=== Using the CSET Specification Template

1. Open your Specification in Visual Studio Code (VSC).
2. Add Document Basecamp as a submodule within your Specification. 
 ** See <<_how_to_add_the_document_basecamp_submodule, Section 4.2. __How to Add the Document Basecamp Submodule__>> for instructions.

3. Copy the following files from Document Basecamp and paste them into your Specification's root directory: 

 * From the *spec folder* in Document Basecamp:

  . README.adoc
  . spec-document-variables.adoc
  . spec-pdf-cover.adoc
  . specification.adoc (_or_ specification-simple.adoc)

 *  From Document Basecamp:

  . acronym_list.adoc
  . definitions.adoc

WARNING: Do not rename these files. Files reference each other by name.

[start=4]
4. Input or edit the variables in your Spec's copy of the *spec-document-variables.adoc* file first. 
 * The variables in this file will be used throughout the guide and the cover page. 

5. Then write or update your Spec's copy of the *specification.adoc* file - this is where the main contents of your Spec will be contained. 
** Use the *specification-simple.adoc* file instead of the specification.adoc file for Simple Specifications. 

6.  Update your Specification's copy of the *definitions.adoc* file to include the terms used throughout your Specification. 
 ** Note that you may add terms to your copy of the definitions.adoc file if necessary. 
 *** You may want to use this language: "For the purposes of this Specification, <xyz term> is used to refer to <fill in your spec-specific definition>."

7. Edit your Spec's copy of the *acronym_list.adoc* to include the acronyms used throughout your Spec. 

8. Update your Spec's copy of the *README.adoc*. 
 ** Note that there is a template for you to fill in. The README template was added in Spring 2022 to improve uniformity across CSET's documents. 

IMPORTANT: You will not edit the *spec-pdf-cover.adoc* file, but this file does need to be copied over from document_basecamp and pasted into your document's root directory for the pdf version of your Specification to be properly generated. 

=== Generating HTML Specifications

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor -D build specification.adoc
----

=== Generating PDF Specifications

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor-pdf -D build spec-pdf-cover.adoc specification.adoc
----

+++<br>+++

== CSET Standards

NOTE: CSET's Standards template directory is located here: https://developer.nasa.gov/CSET/document_basecamp/tree/master/std

=== Using the CSET Standard Template

1. Open your Standard in Visual Studio Code (VSC).

2. Add Document Basecamp as a submodule within your Standard.
 ** See <<_how_to_add_the_document_basecamp_submodule, Section 4.2. __How to Add the Document Basecamp Submodule__>> for instructions.
 
3. Copy the following files from Document Basecamp and paste them into your Standard's root directory: 

 * From the *std folder* in Document Basecamp:

  . README.adoc
  . standard.adoc
  . std-document-variables.adoc
  . std-pdf-cover.adoc

 *  From Document Basecamp:

  . acronym_list.adoc
  . definitions.adoc

WARNING: Do not rename these files. Files reference each other by name.

[start=4]
4. Input or edit the variables in your Standard's copy of the *std-document-variables.adoc* file first. 
** The variables in this file will be used throughout the Standard and the cover page. 

5. Then write or update your Standard's copy of the *standard.adoc* file - this is where the main contents of your Standard will be contained. 
** Note that there is a new variable that needs to be filled in in the *standard.adoc* file: 
*** New variable: :reqkey: 
*** Appears on line 48 of template.
*** See comment block above line 48 in the template for instructions on how to fill in this variable. 
*** All other variables that need to be input or updated are housed in the *std-document-variables.adoc* file.

6.  Update your Standard's copy of the *definitions.adoc* file to include the terms used throughout your Standard. 
 ** Note that you may add terms to your copy of the definitions.adoc file if necessary. 
 *** You may want to use this language: "For the purposes of this Standard, <xyz term> is used to refer to <fill in your standard-specific definition>."

7. Edit your Standard's copy of the *acronym_list.adoc* to include the acronyms used throughout your Standard. 

8. Update your Standard's copy of the *README.adoc*. 
 ** Note that there is a template for you to fill in. The README template was added in Spring 2022 to improve uniformity across CSET's documents.  

IMPORTANT: You will not edit the *std-pdf-cover.adoc* file, but this file does need to be copied over from document basecamp and pasted into your document's root directory for the pdf version of your Standard to be properly generated. 

=== Pre-Build the Standard's Requirements Compliance Matrix

Run this command before running either the HTML or PDF build script *each time* to generate an up-to-date Requirements Compliance Matrix (the std-compliance-matrix.adoc). 

NOTE: Command below requires Python3 installed and configured on system. 

[source]
----
python3 ./document_basecamp/std/build_req_table.py standard.adoc
----

=== Generating HTML Standards

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor -D build standard.adoc
----

=== Generating PDF Standards

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor-pdf -D build std-pdf-cover.adoc standard.adoc
----


+++<br>+++

== Using Github

=== Git Workflow

. If it does not already exist, create a new repository in the ASCS organization.
. Fork the repository from ASCS to your personal account.
. Clone the newly forked repository to your system.
. Create a new branch.
. Make changes in this branch until you are ready to give the changes back to the ASCS repository.
. Push your development branch to your personal repository on GitHub.
. Create a pull request to the ASCS repository.
. Pull request is reviewed and if accepted merged into the ASCS repository.
. Once a pull request has been merged you are free to delete the branch from your personal repository.
. Sync your fork to be in line with the ASCS repository.

=== How to Add the Document Basecamp Submodule


