= Document Basecamp

This repository houses the AsciiDoc templates and styles utilized to create CSET's Standards, Handbook, Specifications.

== Templates
The following subsections provide directions on where to find each of CSET's document template directories, the contents of those directories, and instructions on how to use the files contained in those directories. 

The files contained in each of these directories serve as the format to be used for creating each kind of CSET document. 

=== CSET Handbooks
CSET's Handbook template directory is located in the following location: https://developer.nasa.gov/CSET/document_basecamp/tree/master/hdbk

*This directory contains the following three files:*

* handbook.adoc
* hbk-pdf-cover.adoc
* hdbk-document-variables.adoc

WARNING: Do not rename these files. Files reference each other by name.

*When creating or updating a Handbook* you will need to clone this entire directory (see the section titled _Git Workflow_ below to make sure you have done this correctly).
When you are ready to write or update your Handbook, follow these steps: 

. Input or edit the variables in the *hdbk-document-variables.adoc* file first. The variables in this document will be used throughout the guide and the cover page. 
. Then write or update the *handbook.adoc* file - this is where the main contents of your Handbook will be contained. 

NOTE:  You do not need to edit the *hbk-pdf-cover.adoc* file, but this file does need to be included for the pdf version of your Handbook to be properly generated. 

=== Generating HTML Handbooks

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor -D build handbook.adoc
----

=== Generating PDF Handbooks

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor-pdf -D build hdbk-pdf-cover.adoc handbook.adoc
----

=== CSET Specifications
CSET's Specification template directory is located in the following location: https://developer.nasa.gov/CSET/document_basecamp/tree/master/scs

*This directory contains the following four files:*

* spec-document-variables.adoc
* spec-pdf-cover.adoc
* specification-simple.adoc
* specification.adoc

WARNING: Do not rename these files. Files reference each other by name.

*When creating or updating a Specification* you will need to clone this entire directory (see the section titled _Git Workflow_ below to make sure you have done this correctly).
When you are ready to write or update your Spec, follow these steps: 

. Input or edit the variables in the *spec-document-variables.adoc* file first. The variables in this document will be used throughout the guide and the cover page. 
. Then write or update the *specification.adoc* file - this is where the main contents of your Spec will be contained. 
.. Use the *specification-simple.adoc* file instead of the specification.adoc file for Simple Specifications. 

NOTE:  You do not need to edit the *spec-pdf-cover.adoc* file, but this file does need to be included for the pdf version of your Spec to be properly generated. 


=== Generating HTML Specifications

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor -D build specification.adoc
----

=== Generating PDF Specifications

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor-pdf -D build spec-pdf-cover.adoc specification.adoc
----

=== CSET Standards
CSET's Standards template directory is located in the following location: https://developer.nasa.gov/CSET/document_basecamp/tree/master/std

*This directory contains the following three files:*

* standard.adoc
* std-document-variables.adoc
* std-pdf-cover.adoc

WARNING: Do not rename these files. Files reference each other by name.

*When creating or updating a Standard* you will need to clone this entire directory (see the section titled _Git Workflow_ below to make sure you have done this correctly).
When you are ready to write or update your Standard, follow these steps: 

. Input or edit the variables in the *std-document-variables.adoc* file first. The variables in this document will be used throughout the guide and the cover page. 
. Then write or update the *standard.adoc* file - this is where the main contents of your Standard will be contained. 

NOTE:  You do not need to edit the *std-pdf-cover.adoc* file, but this file does need to be included for the pdf version of your Spec to be properly generated. 

=== Generating HTML Standards

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor -D build standard.adoc
----

=== Generating PDF Standards

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor-pdf -D build std-pdf-cover.adoc standard.adoc
----

== Git Workflow

=== Git Submodule 

Adding the Document Basecamp to a document tree uses the git submodule command. The document_basecamp directory will be added as a submodule in the repository. 

.Command Line Submodule
[source]
----
git submodule add https://developer.nasa.gov/CSET/document_basecamp.git
git add .
git commit -m "adding document_basecamp to document"
git push origin <branch name>
----

=== Continued Maintenance

Cloning or fetching the document_basecamp from a previous commit, this is done in the root of the document. Before you run these commands you should see a .gitmodule file (hidden) and a document_basecamp directory that is empty.

Adding document_basecamp after cloning a repository

[source]
----
git submodule init
git submodule update
----

Updating a submodule

[source]
----
cd document_basecamp
git fetch
git merge -s recursive -Xours origin origin/master
----