:doctype: article
:stylesdir: document_basecamp/
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
:chapter-signifier:
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 5
:toc-placement!:
:xrefstyle: full

= Document Basecamp

This README contains instructions on how to use the AsciiDoc templates to create ASCS standards, specifications, and handbooks. 

'''

TIP: For guidance on how to set up Git and use GitHub, visit the link:https://docs.github.com/en/get-started/quickstart[GitHub Quickstart] page. 

'''

toc::[] 

+++<br>+++

'''

:numbered:

== Prerequisites for Creating New ASCS Documents

The following prerequisites must be met before a new ASCS document can be created:

. A link:https://etads-atlassian.grc.nasa.gov/confluence/x/LYCgB[document preparation form] must be completed and submitted via Confluence. 
. A meeting to discuss and outline the document must be held between the document's primary author, the ASCS technical writer, the ASCS Lead, and any other subject matter experts (SMEs) indicated on the document prep form.
. The ASCS Lead must provide or approve of:

** the name for the document's GitHub repository (e.g., organization-defined_values), and
** the document identifier (e.g., NASA-SPEC-2661.ODVr5).


Once the prerequisites listed above are met, the author may follow the instructions in the following sections to create their new document. 

== ASCS Document Creation: From Start to Finish

This section provides step-by-step instructions that can be followed to *manually* create a new ASCS document - from initial set up to building .pdf and .html files. 

TIP: You can choose to set up and build an ASCS document manually via the instructions in this section or you can use the ASCS Document Scripts. Refer to <<ASCS Document Scripts, Section 3, _ASCS Document Scripts_>> for guidance on using a script to set up and build your ASCS document. 


=== Document Setup Process

NOTE: The instructions below were written specifically for setting up a new ASCS *Standard*. However, the process is the same for specifications and handbooks. In the instructions below, references to standard-specific elements can be substituted with the equivalent elements for specifications and handbooks. 

. Create a repository (repo) for your Standard on GitHub under the link:https://developer.nasa.gov/ASCS[ASCS Organization].

** Reference the GitHub doc link:https://docs.github.com/en/get-started/quickstart/create-a-repo[Create a repo] for guidance. 

. Create a fork of your new repository. Fork your repo to link:https://developer.nasa.gov/ASCS-Dev[ASCS Development].

** Reference the GitHub doc link:https://docs.github.com/en/get-started/quickstart/fork-a-repo[Fork a repo] for guidance. 

IMPORTANT: While an ASCS document is in a draft stage (i.e., prior to publishing v1.0 or an updated version), make all changes to your document in the ASCS fork. 

[start=3]
. Clone your repo, save it locally, and open it in Visual Studio Code (VSC). 

. Add the document_basecamp submodule to your repository. 

** See <<How to Add the Document Basecamp Submodule, Section 4.1, _How to Add the Document Basecamp Submodule_>> of this README for instructions.
 
. Copy the following files from the `document_basecamp` folder and paste them into your Standard's root directory: 

 * From `document_basecamp/std`:
 ** `README.adoc`
 ** `standard.adoc`

 *  From `document_basecamp`:
 ** `.gitignore`
 ** `acronym_list.adoc`
 ** `definitions.adoc`

WARNING: Do not rename these files. Files reference each other by name.

[start=6]
. Open your Standard's copy of `standard.adoc`, located in your Standard's root directory, and:
.. Type in values for all of the applicable document variables, which include (but may not be limited to):
    *** :document-identifier:
    *** :document-title:
    *** :document-version:
.. Write the content of your document. 
** There are several sections of the template that contain sentences that need to be completed by the author, including:
   ... The purpose statement
   ... Section 2.1, _Applicability_

TIP: Be sure to read the guidance and examples provided in comments throughout the `standard.adoc` file to make sure that you are filling in everything appropriately. 

[start=7]
.  Open your Standard's copy of `definitions.adoc`, located in your Standard's root directory, and:
.. un-comment all terms that are used in your document. 
.. add any key terms (in the correct, alphabetical location) that need to be defined in your document and which are not already in the `definitions.adoc` list of terms. 

** Please check new terms and definitions with the ASCS technical writer prior to adding them to your document. 

. Open your Standard's copy of the `acronym_list.adoc`, located in your Standard's root directory, and:

.. un-comment all acronyms that are used in your document. 
.. add any acronyms (in the correct, alphanumerical location) that are used in your document and which are not already in the `acronym_list.adoc`.

. Open your Standard's copy of the `README.adoc` , located in your Standard's root directory, and fill in all of the necessary information. 

=== ASCS Document Build Process

NOTE: The instructions below were written specifically for building the .html and .pdf versions of an ASCS *Standard*. However, the process is mostly the same for all other types of ASCS documents; be sure to see notes highlighting key differences for different kinds of documents. 

*1. Build the Requirements Compliance Matrix*

** All ASCS standards and some specifications contain a Requirements Compliance Matrix.
** For any ASCS document that contains a Requirements Compliance Matrix, the following command must be run *each time* to generate an up-to-date Requirements Compliance Matrix (the std-compliance-matrix.adoc) prior to running either the .html or .pdf build script. 


[source]
----
python3 ./document_basecamp/std/build_req_table.py standard.adoc
----

NOTE: The command above requires Python3 installed and configured on your system. 

[start=2]
*2. Generate the .html file:*

.. Create a `build` folder within your document's root directory prior to running this command, as as the `build` folder is not created upon cloning your repository. 
.. Then, run the command below: 

[source]
----
asciidoctor -D build standard.adoc
----

[start=3]
.. The .html file will appear in the `build` folder. 


*3. Generate the pdf file:*

.. Ensure you have created a `build` folder within your document's root directory prior to running this command, as the `build` folder is not created upon cloning your repository. 
.. Then, run the command below: 

[source]
----
asciidoctor-pdf -D build std-pdf-cover.adoc standard.adoc
----

[start=3]
.. The .pdf file will appear in the `build` folder. 

+++<br>+++


== ASCS Document Scripts

A member of CSET created the link:https://developer.nasa.gov/CSET/Document_Scripts[CSET Document Scripts] repository to aid in the creation of ASCS standards, specifications, and handbooks. 

There are two scripts in the repository linked above; the purpose of each script is summarized in the subsections below. 

=== The ASCS Setup Script

The ASCS Setup Script can be used to start a new document and to detect and correct errors that would otherwise be flagged by the build script later.

=== The ASCS Build Script

The ASCS Build Script is run by entering one simple command (regardless of document type) into command line. Not only does this script build both the html and pdf formats of the document at once, but it also performs a long list of checks that were written into the script in effort to reduce the time and effort required during the document review process to catch frequently-made human errors. 

== Git Quick References

=== How to Add the Document Basecamp Submodule

IMPORTANT: Add the document basecamp submodule before creating a fork of a repository. 

If you *do not* already have the document basecamp submodule in your document's repository, copy and paste the following commands into the Terminal: 

[source]
----
git submodule add https://developer.nasa.gov/CSET/document_basecamp.git
git add .
git commit -m "adding document_basecamp to document"
git push origin <branch name>
----

===  How to Update the Document Basecamp Submodule

If you *do* already have the document basecamp submodule in your document's repository, but it is not up-to-date, copy and paste the following commands into the Terminal: 

[source]
----
git submodule init
git submodule update
cd document_basecamp
git fetch
git merge -s recursive -Xours origin origin/master
cd ..
----

