:doctype: article
:stylesdir: document_basecamp/
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
:chapter-signifier:
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 5
:toc-placement!:
:xrefstyle: full

= Document Basecamp

This README contains instructions on how to use the AsciiDoc templates to create ASCS standards, specifications, and handbooks. 

'''

TIP: For guidance on how to get set up and use GitHub, visit the link:https://docs.github.com/en/get-started/quickstart[GitHub Quickstart] page. This page contains links to step-by-step instructions on how to set up Git, create a new repository, fork a repository, and move through the GitHub workflow. 

'''

toc::[] 

+++<br>+++

'''

:numbered:

== Prerequisites for New ASCS Documents

The following prerequisites must be met before a new ASCS document can be created:

. A link:https://etads-atlassian.grc.nasa.gov/confluence/x/LYCgB[document preparation form] must be completed and submitted via Confluence. 
. A meeting to discuss and outline the document must be held between the document's primary author, the ASCS technical writer, the ASCS Lead, and any other subject matter experts (SMEs) indicated on the document prep form.
. The ASCS Lead must provide or approve of the following:

** A name for the document's GitHub repository (e.g., organization-defined_values)
** The document identifier (e.g., NASA-SPEC-2661.ODVr5)


Once the prerequisites listed above are met, the author may set up their new document. 

== ASCS Document Creation: From Start to Finish

This section provides step-by-step instructions that can be followed to manually create (i.e., from initial set up to building the document) a new ASCS document. 

TIP: You can choose to set up a new ASCS document manually via the instructions in this section, or you can use the ASCS Setup Script. Refer to <<ASCS Document Scripts, Section 3, _ASCS Document Scripts_>> for guidance on using a script to set up your ASCS document. 



CSET's Standards template directory is located here: https://developer.nasa.gov/CSET/document_basecamp/tree/master/std

CSET's Specification template directory is located here: https://developer.nasa.gov/CSET/document_basecamp/tree/master/spec

CSET's Handbook template directory is located here: https://developer.nasa.gov/CSET/document_basecamp/tree/master/hdbk


=== Document Setup Process:

NOTE: The instructions in this section are written specifically for setting up a new ASCS *Standard*. However, the process is the same for all other types of ASCS documents. In the instructions below, references to standard-specific elements can be substituted with the equivalent elements for specifications and handbooks. 


. Create a repository (repo) for your Standard on GitHub under the link:https://developer.nasa.gov/ASCS[ASCS Organization].

** Reference the GitHub doc link:https://docs.github.com/en/get-started/quickstart/create-a-repo[Create a repo] for guidance. 

. Create a fork of your new repository. Fork your repo to link:https://developer.nasa.gov/ASCS-Dev[ASCS Development].

** Reference the GitHub doc link:https://docs.github.com/en/get-started/quickstart/fork-a-repo[Fork a repo] for guidance. 

IMPORTANT: While an ASCS document is in a draft stage (i.e., prior to publishing v1.0 or an updated version), make all changes to your document in the ASCS fork. 

[start=3]
. Clone your repo, save it locally, and open it in Visual Studio Code (VSC). 

. Add the document_basecamp submodule to your repository. 

** See <<How to Add the Document Basecamp Submodule, 4.1, _How to Add the Document Basecamp Submodule_>> of this README for instructions.
 
. Copy the following files from the `document_basecamp` folder and paste them into your Standard's root directory: 

 * From `document_basecamp/std`:
 ** `README.adoc`
 ** `standard.adoc`

 *  From `document_basecamp`:
 ** `.gitignore`
 ** `acronym_list.adoc`
 ** `definitions.adoc`

WARNING: Do not rename these files. Files reference each other by name.

[start=6]
. Open your Standard's copy of `standard.adoc`, located in the root directory of your repository, and:
.. input all of the necessary document variables. 
.. write the content of your document. 

TIP: Read the guidance and examples provided in comments throughout the `standard.adoc` file to make sure that you are filling in everything appropriately. 

[start=7]
.  Open your Standard's copy of `definitions.adoc`, located in the root directory of your repository, and:
.. un-comment all terms that are used in your document. 
.. add any key terms (in the correct, alphabetical location) that need to be defined in your document and which are not already in the `definitions.adoc` list of terms. 

** Please check new terms and definitions with the ASCS technical writer prior to adding them to your document. 

. Open your Standard's copy of the `acronym_list.adoc`, located in the root directory of your repository, and:

.. un-comment all acronyms that are used in your document. 
.. add any acronyms (in the correct, alphanumerical location) that are used in your document and which are not already in the `acronym_list.adoc`.

. Open your Standard's copy of the `README.adoc` , located in the root directory of your repository, and fill in all of the necessary information. 

=== ASCS Document Build Process

*ELYSE ADD INTRO TO SAY:*

* *THIS IS THE MANUAL STEP_BY_STEP PROCESS - YOU CAN ALSO USE THE BUILD SCRIPT*


=== Building Requirements Compliance Matrix

Run this command before running either the HTML or PDF build script *each time* to generate an up-to-date Requirements Compliance Matrix (the std-compliance-matrix.adoc). 

NOTE: Command below requires Python3 installed and configured on system. 

[source]
----
python3 ./document_basecamp/std/build_req_table.py standard.adoc
----

=== Generating HTML Standards

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor -D build standard.adoc
----

=== Generating PDF Standards

IMPORTANT: Build dir is not created upon clone. Create the build dir before running these commands. 

[source]
----
asciidoctor-pdf -D build std-pdf-cover.adoc standard.adoc
----

+++<br>+++


== ASCS Document Scripts

A member of CSET created the link:https://developer.nasa.gov/CSET/Document_Scripts[CSET Document Scripts] repository to aid in the creation of CSET's standards, specifications, and handbooks. 

There are two scripts in the repository linked above:

. *The CSET Build Script:* The CSET Build Script is run by entering one simple command (regardless of document type) into command line. Not only does this script build both the html and pdf formats of the document at once, but it also performs a long list of checks that were written into the script in effort to reduce the time and effort required during the document review process to catch frequently-made human errors. 

. *The CSET Setup Script:* The CSET Setup Script can be used to start a new document and to detect and correct errors that would otherwise be flagged by the build script later.

== Git Quick References

=== How to Add the Document Basecamp Submodule

IMPORTANT: Add the document basecamp submodule before creating a fork of a repository. 

If you *do not* already have the document basecamp submodule in your document's repository, copy and paste the following commands into the Terminal: 

[source]
----
git submodule add https://developer.nasa.gov/CSET/document_basecamp.git
git add .
git commit -m "adding document_basecamp to document"
git push origin <branch name>
----

===  How to Update the Document Basecamp Submodule

If you *do* already have the document basecamp submodule in your document's repository, but it is not up-to-date, copy and paste the following commands into the Terminal: 

[source]
----
git submodule init
git submodule update
cd document_basecamp
git fetch
git merge -s recursive -Xours origin origin/master
cd ..
----

