= Security Configuration Specification Name
:doctype: book
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:
:document-type: NASA TECHNICAL SPECIFICATION
:document-identifier: NASA-SPEC-26XX
:document-title: SPECIFICATION NAME
:document-subtitle: SECURITY CONFIGURATION SPECIFICATION
:approved-date: 2018-08-XX
:version: v1.5-DRAFT
:revision-date: 2018-07-30
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
:measurement-system: MEASUREMENT SYSTEM IDENTIFICATION
:notitle:
:noheader:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font


include::document_basecamp/title_page.adoc[]
include::document_basecamp/foreword.adoc[]

toc::[]


[dedication]
DOCUMENT HISTORY LOG
====================

[width="100%",cols="1,1,1,2,4"]
|====

|Status
|Document Revision
|Change Number
|Approval Date
|Description

|====

<<<

:numbered:
== Scope

=== Purpose

The purpose of this NASA Technical Standard is (add one-to-two sentence description).

=== Applicability

This Standard is applicable to technology programs and projects managed by federal employee or contractor Information System Owners (ISOs) at NASA Headquarters and NASA Centers, including Component Facilities and Technical and Service Support Centers. This Standard applies to the Jet Propulsion Laboratory (JPL), a Federally Funded Research and Development Center (FFRDC), and other non-Agency facility contractors only to the extent specified or referenced in applicable contracts.

NPR 2810.1x, Security of Information Technology, clearly defines the role and responsibilities of information system owners (ISO) in relation to Agency information systems. These responsibilities include:

- Acquiring, developing, integrating, operating, modifying, and maintaining information systems.
- Ensuring system-level implementation of all Agency and Center requirements.
- Taking appropriate actions to identify and minimize or eliminate information system security deficiencies and weaknesses.

Standard guidance will be added, replaced, or removed as appropriate to align these responsibilities with Agency information security- and privacy-related program and project requirements.

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized Enterprise Technology Assessments and Digital Standards (ETADS) within the ETADS Charter, ยง2, to create binding Technical Standards related to Agency security topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes ETADS as a standards-developing organization within the Agency. NTSP provides access to all technical standards at:

https://standards.nasa.gov/

=== Tailoring

Tailoring of this NASA Technical Standard for application to a specific program, project, or system shall be formally documented as part of program or project requirements and approved by the responsible Information System Owner and Authorizing Official.
