// Replace the title below with your document's identifier and title:

= NASA-SPEC-XXXX, _Document Title_

:numbered:

== DESCRIPTION
// COPY AND PASTE PURPOSE STATEMENT FROM SPEC HERE. 

The purpose of this NASA Technical Specification is to *(COMPLETE THIS SENTENCE WITH the STATEMENT OF PURPOSE FOR THIS SPEC)*.

NOTE: Comments, concerns, and all other feedback on this Specification can be submitted via email to NASA-DL-ASCS-TECHNICAL@mail.nasa.gov.


== SUPPLEMENTAL RESOURCES

////
The content that goes in this section is specific to your document. 
 
 e.g.:  
    - Windows OS specs will include subsections for GPO reports, objects, templates, etc.
    - macOS and Linux OS specs will include subsections for collections of scripts and configuration profiles
   
Note: if you don't need this section, comment it out! :) 
////

== DOCUMENT HISTORY

// Highlights = Include current version and last version 
// Only include big important changes in the description

.Highlights from Document History 
[%header,width="100%",cols="1,3"]
|====
|Document Version
|Important Changes Made

|{document-version}
a|* example
* example


|vx.x 
a|* example
*  example
|====

