include::spec-document-variables.adoc[]


= {document-identifier}, _{document-title}_

:numbered:

== DESCRIPTION
This ASCS specification defines security configuration settings for *INSERT NAME OF APP OR OS*.

NOTE: Comments, concerns, and all other feedback on this Specification can be submitted via email to NASA-DL-ASCS-TECHNICAL@mail.nasa.gov.

== GUIDE

////
insert html link to guide below

 example:

 * link:https://developer.nasa.gov/ASCS/windows_11/releases/download/v1.0/NASA-SPEC-2601OS.Win11.Security.Configuration.Specification.v1.0.html[{document-title}]

////

* link:INSERTLINK[{document-title}]



// Edit the link below: 
All HTML and PDF documents will be maintained within link:https://developer.nasa.gov/ASCS/INSERTLINK[GitHub Releases].

== SUPPLEMENTAL RESOURCES

////
The content that goes in this section is specific to your document. 
 
 e.g.:  
    - Windows OS specs will include subsections for GPO reports, objects, templates, etc.
    - macOS and Linux OS specs will include subsections for collections of scripts and configuration profiles
   
Note: if you don't need this section, comment it out! :) 
////

== DOCUMENT HISTORY

// Highlights = Include current version and last version 
// Only include big important changes in the description

.Highlights from Document History 
[%header,width="100%",cols="1,3"]
|====
|Document Version
|Important Changes Made

|{document-version}
a|* example
* example


|vx.x 
a|* example
*  example
|====

// Edit the link below: 

NOTE: For a complete, detailed history of changes made to this document, see the link:CHANGELOG.adoc[Full Changelog]. 
