// Replace the title below with the document's identifier and title:

= NASA-SPEC-XXXX, _Document Title_

:numbered:

== Purpose
// COPY PURPOSE STATEMENT FROM THE SPEC AND PASTE BELOW: 

The purpose of this NASA Technical Specification is to *(COMPLETE THIS SENTENCE WITH the STATEMENT OF PURPOSE FOR THIS SPEC)*.

NOTE: Comments, concerns, and all other feedback on this Specification can be submitted via email to mailto:NASA-DL-ASCS-TECHNICAL@mail.nasa.gov[NASA-DL-ASCS-TECHNICAL@mail.nasa.gov].


== Supplemental Resources

////
The content that goes in this section is specific to your document. 
 
 e.g.:  
    - Windows OS specs will include subsections for GPO reports, objects, templates, etc.
    - macOS and Linux OS specs will include subsections for collections of scripts and configuration profiles
   
Note: if you don't need this section, comment it out! :) 
////


== Document History

=== Full Changelog
For a complete, detailed revision history, reference the link:changelog.adoc[CHANGELOG] file.


=== Highlights
The table below provides a brief summary of changes that were made to the document each time an updated version was published. 

// COPY DOCUMENT HISTORY LOG FROM THE SPEC AND PASTE BELOW.

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Date Approved
|Description

|
| 
|

|====