:doctype: book
ifdef::backend-pdf[]
:front-cover-image: image::build/spec-pdf-cover.pdf[]
endif::[]
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
ifdef::backend-html5[]
:toc: macro
:toc-placement!:
endif::[]
:toc-title: TABLE OF CONTENTS
:toclevels: 3
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

// NOTE: include statement need blank line before and after

include::spec-document-variables.adoc[]

////
DOCUMENT VARIABLES (that are not on cover page) DESCRIPTIONS:
  function:            Application function (e.g., web browser, media player, etc.)
  application:         The name of the OS or Application 
  specificationtype:   Enter either "operating system" or "application"
  minversion:          Minimum application version required
  removaldate:         Required removal date from the environment
  applicability:      If this spec is applicable to all computing systems, enter "all".
  *if it's only applicable to systems using this OS or application, delete "all" and leave value blank*
////

// Document variables:
:function:
:application:
:specificationtype:
:minversion:
:removaldate:
:applicability: all

:noheader:
:nofooter:

ifdef::backend-pdf[]
= {application} NASA Technical Specification
{document-subtitle}
:toc: preamble
endif::[]

ifdef::backend-html5[]
= {application} NASA Technical Specification

// NOTE: include statement need blank line before and after

include::document_basecamp/title_page.adoc[]

toc::[]

endif::[]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row! 
  Oldest/first version in the bottom row!

  You must *add a row to the top of the table* each time a new version of the Spec is published.
 
  Track drafts and include descriptions for each draft while the document is out for review. 

  But be sure to DELETE DRAFT TRACKING and update the approved date when it is signed and ready to be published. 

  The description box must not be left blank, but it should be brief. 
   Example descriptions: "Updated to be applicable to xyz"

   NOTE: 
    Approval Date: this will automatically be pulled from the document-variables.adoc file.

    If you are writing an updated version of a Spec, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log
ifdef::backend-pdf[]
:!nofooter:
:!noheader:
endif::[]

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Date Approved
|Description

|{document-version}
|{approved-date}
|
|====

<<<

////
FOREWORD:
 Note that this template is worded to best suit Specs that fall under Standard 2601.

 If your spec does not fall under Standard 2601 - make sure to edit paragraph 3 so that it is accurate for your spec. 
////

== Foreword

This NASA Technical Specification is published by the National Aeronautics and Space Administration (NASA) to describe technical requirements for purchased or in-house items, services, functions, or processes for NASA programs and projects.

This NASA Technical Specification is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other Agency documents. This Specification also applies to the Jet Propulsion Laboratory (JPL) (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

Adherence to this NASA Technical Specification ensures compliance with NASA-STD-2601, _Minimum Cybersecurity Requirements for Computing Systems_, which defines operating system and application security requirements that must be implemented on NASA information systems. This Specification provides the enforceable, measurable details of NASA-STD-2601.

Comments, concerns, and all other feedback on this Specification can be submitted via email to NASA-DL-ASCS-TECHNICAL@mail.nasa.gov.


+++<br>+++

Refer to link:https://cset.nasa.gov/latest/nasa-spec-2600[NASA-SPEC-2600], _Enumeration of ASCS Cybersecurity Requirements_ (Signed PDF).

+++<br>+++


////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.
  
  Please be sure to read comment blocks for instructions. 
////

:numbered:

////
SCOPE:
 The name of the OS or App will be automatically input as long as you have properly filled in the Document Variables section at the top of this Spec. 

 If your Spec is not a configuration Spec, you may also need to rewrite the Purpose and Applicability sections to fit your Spec. - Please read the comment blocks above each subheading. 
////

== Scope

////
Purpose: 
 If your spec does not fall under Standard 2601/ is not a configuration Spec:
   Make sure to edit the Purpose so that it is accurate for your spec. 
   "define" is probably the best verb for Specification purpose statements. establish = for standards; provide guidance = for handbooks
////

=== Purpose

The purpose of this NASA Technical Specification is to define version and configuration requirements for {application} deployment and operation.

////
Applicability: 
 There are two options for sentence 1 under Applicability - choose the one that applies to your spec to make visible. 
     e.g.:
       SEP is applicable to all computing systems = choose first option.
       An Adobe spec would only be applicable to systems that have Adobe.  = choose second option. 
 
 If your spec does not fall under Standard 2601/ is not a configuration Spec:
   Make sure to edit paragraph 1 under Applicability so that it is accurate for your spec. 
////
=== Applicability

ifeval::[ "{applicability}" == "all" ]
This NASA Technical Specification is applicable to all computing systems.
endif::[]

ifeval::[ "{applicability}" != "all" ]
This NASA Technical Specification is applicable to all computing systems using {application}. 
endif::[]

This NASA Technical Specification is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other Agency documents. This Specification also applies to JPL, other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

=== Tailoring

Any and all risk-based decisions (RBDs) to tailor this NASA Technical Specification in order to meet the needs of a specific program, project, or system *_SHALL_* be approved by the responsible Information System Owner (ISO) and Authorizing Official (AO) and formally documented by the ISO or system administrators in the System Security Plan (SSP) under program or project requirements. 

The AO *_SHALL_* ensure that only systems posing an acceptable level of risk to Agency assets, data, and personnel are approved for production operation and that the ISO *_SHALL_* ensure all necessary documentation is produced and maintained.

NOTE: Some NASA Technical Specifications include "_critical_" configuration settings. "_Critical_" configuration settings *_SHALL NOT_* be eligible for any modifications through the application of an RBD.

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at: https://standards.nasa.gov/. 

In accordance with NPR 2810.1__x__, _Security of Information and Information Systems_, requirement 3.4.2.2, ISOs *_SHALL_* implement the requirements and settings defined in all applicable standards and specifications established by ASCS. 

+++<br>+++

////
APPLICABLE DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  
  List documents in alphanumeric order based on their Document Number or Descriptor.

  Use YOURLS to link to documents and link the Document Number or Descriptor.
////

== Applicable Documents

The documents listed in this section contain provisions that constitute requirements of this NASA Technical Specification. These documents can serve as additional support in meeting the requirements defined in this Specification. 

NOTE: A suffix of __x__ on a document identifier indicates that the latest issuance of the document applies.

=== Government Documents

// NOTE: based on your document's specific needs, make visible any of the document tables that are commented out below: 

////
.White House Releases
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////

.NASA Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
|https://cset.nasa.gov/latest/nasa-spec-2600[NASA-SPEC-2600] |_Enumeration of ASCS Cybersecurity Requirements_
|link:https://cset.nasa.gov/latest/nasa-std-2601[NASA-STD-2601]| _Minimum Cybersecurity Requirements for Computing Systems_ 
|link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1__x__]| _Security of Information Technology_
|===


////
.DISA Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////
.NIST Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////
.Other Government Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////

////
=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


+++<br>+++

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  Add and remove acronyms as needed. 
  List acronyms, abbreviations, and definitions in alphabetical order.
////

== Acronyms, Abbreviations, and Definitions

include::acronym_list.adoc[]

// NOTE: If you don't need the Definitions table, change section title to: == Acronyms and Abbreviations

////

include::definitions.adoc[]

////

+++<br>+++

== Version and Lifecycle

This Specification applies to the {specificationtype} defined in the chart below, as well as to any more recent version(s) of this {specificationtype}.


////
All fields in this table should be automatically populated from the Document Variables  
////

[cols="25%h,75%"]
|====
ifeval::[ "{function}" != "" ]
|Function
|{function}
endif::[]
ifeval::[ "{application}" != "" ]
|Application
|{application}
endif::[]
ifeval::[ "{minversion}" != "" ]
|Minimum Version
|{minversion}
endif::[]
ifeval::[ "{removaldate}" != "" ]
|Required Removal Date
|{removaldate}
endif::[]

|====

+++<br>+++

== Security Configurations

=== Critical Severity Settings

_Critical_ severity settings *_SHALL_* be adhered to, as they are monitored, scored, and reported to the Department of Homeland Security (DHS).

* _Critical_ severity settings target any vulnerability which, if exploited, would directly and immediately result in the loss of confidentiality, integrity, or availability. 
* _Critical_ severity settings are reported by the Continuous Diagnosis and Mitigation (CDM) Defend Dashboard and/or mandated by Federal policy.
* Deviations from _critical_ severity settings require approval from the Agency CIO. 

=== High Severity Settings

_High_ severity settings *_SHALL_* be adhered to, as they are monitored, scored, and reported to NASA.

* _High_ severity settings target any vulnerability which, if exploited, would directly and immediately result in the loss of confidentiality, integrity, or availability. 
* Deviations from _high_ severity settings require approval from the Agency CIO. 

=== Medium Severity Settings
	
_Medium_ severity settings *_SHALL_* be adhered to, as they are monitored, scored, and reported to NASA. 

* _Medium_ severity settings target any vulnerability which, if exploited, has the potential to result in the loss of confidentiality, integrity, or availability.

=== Low Severity Settings

_Low_ severity settings are expected to be implemented unless there is a justifiable cause not to. 

* _Low_ severity settings target any vulnerability which, if exploited, degrades measures to protect against the loss of confidentiality, integrity, or availability.




////
RECOMMENDED SETTINGS REFERENCE:
 NOTE: This section has been commented out, as it will be applicable to a minority of Specifications. 
 
      If the Specification you are writing DOES include Recommended Settings, be sure move the bottom of this comment block up to allow the section to be visible.


=== Recommended Settings

This section contains _recommended_ security configuration settings. 

_Recommended_ settings are not required, but they are deemed highly beneficial by ASCS. These settings are expected to be implemented, unless there is a justifiable cause not to. However, _recommended_ settings that are not implemented will not be scored or reported by the Agency.
////


////
GENERAL OPERATIONAL GUIDANCE:
 NOTE: This section has been commented out, as it will be applicable to a minority of Specifications. 
 
       If the Specification you are writing DOES include General Operational Guidance, be sure move the bottom of this comment block up to allow the section to be visible.

== General Operational Guidance
  (Input Content as needed).

////

+++<br>+++

////
APPENDIX SECTION
 Note:
   Appendix is commented out - move the comment block if applicable. 

  Appendices are numbered differently then the rest of the document, so make sure to use 3 or more markers on subsection
    titles (=== SUBSECTION). If you drop to 2 markers (==) it will start normal numbering again.
  Content of the appendix will format for sections and subsections, but not number them.
  
  It is appropriate to continue using heading tags (===) as normal.
  
  Appendices will be lettered based on the [appendix] tag, so the example title will appear as
   APPENDIX A: TITLE OF APPENDIX

  Additional appendices can be used by the [appendix] tag immediately followed on the next line with a
    2 marker title (== APPENDIX TITLE). following appendix will use appropriate letters (B, C, D . . .)


[appendix]
== TITLE OF APPENDIX

////
