:doctype: book
// Document Setup
// HTML
:stylesdir: document_basecamp/
//:stylesheet: asciidoctor-draft.css
//:stylesheet: asciidoctor-provisional.css
:stylesheet: asciidoctor.css
// PDF
:pdf-fontsdir: document_basecamp/fonts/
:pdf-themesdir: document_basecamp/
//:pdf-theme: asciidoctor-pdf-draft.yml
//:pdf-theme: asciidoctor-pdf-provisional.yml
:pdf-theme: asciidoctor-pdf.yml
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
:chapter-signifier:
// Table of Contents
:toc: macro
:toc-placement!:
:toc-title: TABLE OF CONTENTS
:toclevels: 3
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

// Title Page Variables
:document-type: NASA TECHNICAL SPECIFICATION
:document-identifier: NASA-SPEC-2XXX
// document-title:  USE ALL CAPS. If using acronyms in title, check with Sean for approval. 
:document-title: DOCUMENT TITLE
:document-subtitle: SECURITY CONFIGURATION SPECIFICATION
////
approved-date: 
 Input the approved date only when publishing.             
 Leave blank until then.  
 Date format: year-month-date:  20XX-XX-XX
////
:approved-date:
// document-version: e.g., v1.0,  v1.1, v2.0 etc.
:document-version: vx.x
// is-draft: Is this document a draft?
:is-draft: True
// draft-stage: e.g.  "Draft", "Informal Draft", "Formal Draft"
:draft-stage: Draft
// revision-date: remove "//" from line below and input revision date if needed (e.g., vX.X.X)
// :revision-date: 20XX-XX-XX
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
// superseding-document: leave commented out if N/A, remove "//" on lines below and input doc number if needed
// :superseding-document: NASA-SPEC-2XXX
// :superseding-document-version: vx.x


// Customize document header
ifeval::["{is-draft}" == "True"]
:document-header: {document-identifier} {document-version} {document-stage}
endif::[]
ifeval::["{is-draft}" != "True"]
:document-header: {document-identifier} {document-version}
endif::[]

////
*DOCUMENT VARIABLES (that are not on cover page) DESCRIPTIONS:*
  function:            Application function (e.g., web browser, media player, etc.)
  application:         The name of the OS or Application 
  specificationtype:   Enter either "operating system" or "application"
  minversion:          Minimum application version required
  removaldate:         Required removal date from the environment
  applicability:       If this spec is applicable to all computing systems, enter "all". 
                       If it's only applicable to systems using this OS or application, delete "all" and leave value blank*
////

// DOCUMENT VARIABLES (that are not on cover page):
:function:
:application:
:specificationtype:
:minversion:
:removaldate:
:applicability: all

:noheader:
:nofooter:

= {application} NASA Technical Specification

// the include statement requires a blank line before and after

include::document_basecamp/title_page.adoc[]

toc::[]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row! 
  Oldest/first version in the bottom row!

  You must *add a row to the top of the table* each time a new version of the Spec is published.

  The description box must not be left blank, but it should be brief. 
   Example descriptions: "Updated to be applicable to xyz"

  Approval Date: this will automatically be pulled from the document-variables.adoc file.

  If you are writing an updated version of a Spec, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Date Approved
|Description

|
|{approved-date}
|
|====

<<<

== Foreword

This NASA Technical Specification is published by the National Aeronautics and Space Administration (NASA) to describe technical requirements for purchased or in-house items, services, functions, or processes for NASA programs and projects.

This NASA Technical Specification is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other NASA documents. This Specification also applies to the Jet Propulsion Laboratory (JPL) (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

Adherence to this NASA Technical Specification ensures compliance with NASA-STD-2601, _Minimum Cybersecurity Requirements for Computing Systems_, which defines operating system and application security requirements that must be implemented on NASA information systems. This Specification provides the enforceable, measurable details of NASA-STD-2601.

Comments, concerns, and all other feedback on this Specification can be submitted via email to mailto:NASA-DL-ASCS-TECHNICAL@mail.nasa.gov[NASA-DL-ASCS-TECHNICAL@mail.nasa.gov].

+++<br>+++

ifeval::["{is-draft}" == "False"]
Refer to link:https://cset.nasa.gov/latest/nasa-spec-2600[NASA-SPEC-2600], _Enumeration of ASCS Cybersecurity Requirements_ for signature.

+++<br>+++
endif::[]



////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.
  
  Please be sure to read comment blocks for instructions. 
////

:numbered:

////
SCOPE:
 The name of the OS or App will be automatically input as long as you have properly filled in the Document Variables section at the top of this Spec. 
////

== Scope

=== Purpose

The purpose of this NASA Technical Specification is to define version and configuration requirements for {application} deployment and operation.

////
*Applicability:* 
 The value that you put for the variable for applicability (on line 52) will automatically input the correct sentence, but please proof read it to make sure it makes sense. 
////

=== Applicability

ifeval::[ "{applicability}" == "all" ]
This NASA Technical Specification is applicable to all computing systems.
endif::[]

ifeval::[ "{applicability}" != "all" ]
This NASA Technical Specification is applicable to all computing systems using {application}. 
endif::[]

This NASA Technical Specification is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other NASA documents. This Specification also applies to JPL, other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

=== Tailoring

Each security configuration setting defined in this NASA Technical Specification is assigned an ASCS severity rating of _Critical_, _High_, _Medium_, or _Low_. The process for deviating from security configuration settings varies based on each setting's ASCS severity rating.

NOTE: Each security configuration setting protects against the exploitation of a vulnerability, and ASCS severity ratings are assigned to settings based on the potential impact that a system would incur if the associated vulnerability were exploited. This is why the process for deviating from settings is based on severity rating. 

*_Critical_ and _High_ Severity Ratings:*

Security configuration settings with _Critical_ or _High_ severity ratings *_SHALL NOT_* be tailored out of the System Security Plan (SSP). If a specific program, project, or system is unable to fully implement a setting with a _Critical_ or _High_ severity rating, a Plan of Action and Milestones (POA&Ms) or risk-based decision (RBD) addressing this need *_SHALL_* be approved by the NASA Chief Information Officer (CIO) or designee, and the RBD *_SHALL_* be formally documented in the system's SSP under program or project requirements.

*_Medium_ Severity Rating:*

If a specific program, project, or system is unable to fully implement a setting with a _Medium_ severity rating a POA&M or RBD addressing this need *_SHALL_* be approved by the responsible Information System Owner (ISO) and the Authorizing Official (AO) (or Authorizing Official Designated Representative (AODR), if applicable) and formally documented by the ISO or system administrator(s) in the SSP under program or project requirements. The AO *_SHALL_* ensure that only systems posing an acceptable level of risk (LOR) to NASA assets, data, and personnel are approved for production operation and that all necessary documentation is produced and maintained.

*_Low_ Severity Rating:*

Security configuration settings with a _Low_ severity rating are expected to be implemented unless there is a justifiable cause not to. Deviations from security configuration settings with a Low severity rating will not impact a system's compliance score.

<<<<

=== Authority

The NASA Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within NASA. 

In accordance with link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1F], _Security of Information and Information Systems_, ISOs *_SHALL_* implement the requirements and settings defined in all applicable standards and specifications established by ASCS. 


+++<br>+++

////
APPLICABLE DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  
  List documents in alphanumeric order based on their Document Identifier.

  *Use YOURLS* to link to documents and *link the Document Identifier*.
////

== Applicable Documents

=== Requirements Documents

The documents listed in this section contain provisions that constitute requirements of this NASA Technical Specification. These documents can serve as additional support in meeting the requirements defined in this Specification. 

NOTE: A suffix of __x__ on a document identifier indicates that the latest issuance of the document applies.

==== Government Documents

// Based on your document's specific needs, make visible any of the document tables that are commented out below: 

////
.White House Releases
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////

.National Aeronautics and Space Administration (NASA) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
|link:https://cset.nasa.gov/latest/nasa-spec-2600[NASA-SPEC-2600]|_Enumeration of ASCS Cybersecurity Requirements_
|link:https://cset.nasa.gov/latest/nasa-std-2601[NASA-STD-2601]|_Minimum Cybersecurity Requirements for Computing Systems_ 
|link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1F]|_Security of Information and Information Systems_
|===


////
.Defense Information Systems Agency (DISA) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////
.National Institute of Standards and Technology (NIST) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////
.Other Government Documents
[%header]
|===
|Document Title
| 
|===
////

////
==== Non-Government Documents

[%header]
|===
|Document Title
| 
|===
////


////
SUPPLEMENTAL GUIDANCE: 
Add any websites, handbooks, etc. that you used as a reference while writing this NASA Technical Specification.
 - List documents in alphabetical order based on the title.
 - *Use YOURLS* to link to documents and *link the title of the document*.
////

////
=== Supplemental Guidance

The resources listed in this section were used as a reference while writing this NASA Technical Specification and may serve as additional support in implementing the requirements defined in this Specification.

[%header]
|===
|Title
| 
|
|===
////

+++<br>+++

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  NOTE: If you do not need the Definitions table, comment it out and change section title to: == Acronyms and Abbreviations
////

== Acronyms, Abbreviations, and Definitions

include::acronym_list.adoc[]


<<<

include::definitions.adoc[]

<<<

+++<br>+++

== Version and Lifecycle

This Specification applies to the {specificationtype} defined in the chart below, as well as to any more recent version(s) of this {specificationtype}.


////
All fields in this table will be automatically populated from the Document Variables  
////

[cols="25%h,75%"]
|====
ifeval::[ "{function}" != "" ]
|Function
|{function}
endif::[]
ifeval::[ "{application}" != "" ]
|Application
|{application}
endif::[]
ifeval::[ "{minversion}" != "" ]
|Minimum Version
|{minversion}
endif::[]
ifeval::[ "{removaldate}" != "" ]
|Required Removal Date
|{removaldate}
endif::[]

|====

+++<br>+++

////

////


== Security Configurations


=== Critical Severity Settings

_Critical_ severity settings *_SHALL_* be adhered to, as they are monitored, scored, and reported to the Department of Homeland Security (DHS).

* _Critical_ severity settings target any vulnerability which, if exploited, would directly and immediately result in the loss of confidentiality, integrity, or availability. 
* _Critical_ severity settings are reported by the Continuous Diagnosis and Mitigation (CDM) Defend Dashboard and/or mandated by Federal policy.
* Deviations from _critical_ severity settings require approval from the NASA CIO or CIO designee.  

=== High Severity Settings

_High_ severity settings *_SHALL_* be adhered to, as they are monitored, scored, and reported to NASA.

* _High_ severity settings target any vulnerability which, if exploited, would directly and immediately result in the loss of confidentiality, integrity, or availability. 
* Deviations from _high_ severity settings require approval from the NASA CIO or CIO designee. 

=== Medium Severity Settings
	
_Medium_ severity settings *_SHALL_* be adhered to, as they are monitored, scored, and reported to NASA. 

* _Medium_ severity settings target any vulnerability which, if exploited, has the potential to result in the loss of confidentiality, integrity, or availability.

=== Low Severity Settings

_Low_ severity settings are expected to be implemented unless there is a justifiable cause not to. 

* _Low_ severity settings target any vulnerability which, if exploited, degrades measures to protect against the loss of confidentiality, integrity, or availability.


+++<br>+++

////
APPENDIX SECTION

Appendices will be lettered (not numbered). 

Appendices can be added by putting the marker [appendix] on one line, and then, directly underneath (on the next line), write the 2 marker title for the appendix.
  Example: 
    [appendix]
    == Title of Appendix 

  Example title will appear as:
   APPENDIX A: Title of Appendix 

////

////

[appendix]
== Title of Appendix 

////


