:doctype: book
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:

// Title Page Variables
:document-type: NASA TECHNICAL SPECIFICATION
:document-identifier: NASA-SPEC-2XXXX
// document-title: No acronyms in title - spell them out
:document-title: DOCUMENT TITLE
:document-subtitle: SECURITY CONFIGURATION SPECIFICATION
// approved-date: input the approved date only when signed (NOTE: this variable will automatically be plugged into the document history log)
:approved-date: 20XX-XX-XX
// version: "Initial Draft", "Informal Draft", "Formal Draft", "Final Draft", "Baseline"
:version: Initial Draft
:revision-date: 20XX-XX-XX
// comment block out the cover-page-marks before publishing
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
:superseding-document: NASA-SPEC-2XXX
:superseding-document-revision: XXXX
// xrefstyle full shows the section number and title
:xrefstyle: full

////
DOCUMENT VARIABLES:
 Description of fields:
  function:     Application function (e.g., web browser, media player, etc.)
  application:  The name of the OS or Application 
  minversion:   Minimum application version required
  removaldate:  Required removal date from the environment

////

// Document variables:
:function:
:application:
:minversion:
:removaldate:

= {application} Security Configuration Specification

// Do not show the footer for HTML
ifdef::backend-html5[]
:nofooter:
endif::[]

// An additional title is needed for PDF output
ifdef::backend-pdf[]
[colophon]
= {nbsp}
endif::[]

// Title Page
include::document_basecamp/title_page.adoc[]

toc::[]


////
DOCUMENT HISTORY LOG:
  Newest version at the top of the table!
  Oldest/first version in the bottom row!

  You must add a row to the top of the table each time a new version of the Spec is published.
 
  DO NOT TRACK DRAFTS (informal draft, formal draft, etc.) in the Document History table!
    Only update this table to include signed and published versions. 

  The description box must not be left blank, but it should be brief. 
  Example descriptions: 
    "Baseline", "Updates based on DEFEND AWARE", "Small DNS over HTTP update"

NOTE: 
 Approval Date:  this will automatically be pulled from the VARIABLES at the top. 
 If you are writing an updated version of a Standard, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Approval Date
|Description

|1.0
|{approved-date}
|
|====

<<<


== Foreword

This Security Configuration Specification is approved for use by NASA Headquarters and all NASA Centers. It is intended to describe configuration setting requirements for purchased or in-house items, services, functions, or processes for NASA programs and projects. It provides the enforceable, measurable details of a Technical Standard.

Adherence to this Specification ensures compliance with NASA-STD-2601, _Minimum Cybersecurity Requirements for Computing Systems_, which defines operating system and application security requirements that must be implemented on NASA information systems.

Requests for information, corrections, or additions to this Specification should be directed to the NASA John H. Glenn Research Center at Lewis Field (GRC), Cybersecurity Standards and Engineering Team (CSET), MS 142-5, Cleveland, OH, 44135 or to nasa-ascs-staff@lists.nasa.gov.


+++<br><br><br><br><br><br><br>+++


Michael Witt 


Senior Agency Information Security Officer

////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.
  
  Please be sure to read comment blocks for instructions. 
////

:numbered:

////
SCOPE:
 The name of the OS or App will be automatically input as long as you have properly filled in the Document Variables section at the top of this Spec. 

 If your Spec is not a configuration Spec, you may also need to rewrite the purpose to fit your Spec.
////

== Scope

=== Purpose

The purpose of this Security Configuration Specification is to provide mandatory version and configuration guidance for {application} deployment and operation.

=== Applicability

This Specification is applicable to computing devices managed by federal employee or contractor Information System Owners (ISOs) at NASA Headquarters and NASA Centers, including Component Facilities and Technical/Service Support Centers. 

This Specification applies to the Jet Propulsion Laboratory (JPL), a Federally Funded Research and Development Center (FFRDC), and other non-Agency facility contractors only to the extent specified or referenced in applicable contracts. 

NPR 2810.1x, _Security of Information Technology_, clearly defines the role and responsibilities of ISOs in relation to Agency information systems. These responsibilities include:

* acquiring, developing, integrating, operating, modifying, and maintaining information systems;
* ensuring system-level implementation of all Agency and Center requirements; and
*	taking appropriate actions to identify and minimize or eliminate information system security deficiencies and weaknesses.

ISO responsibilities will be added, replaced, or removed from NPR 2810.1x when such changes are deemed appropriate by the Cybersecurity and Privacy Program (CSPP) in order to align these responsibilities with Agency information security- and privacy-related program and project requirements.


=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at:

https://standards.nasa.gov/

=== Tailoring

Tailoring of this Security Configuration Specification to meet the needs of a specific program, project, or system _SHALL_ be formally documented as part of program or project requirements and approved by the responsible ISO and Authorizing Official (AO).

////
APPLICABLE DOCUMENTS:

  The tables in this section should be in alpha-numerical order according to Document Number or Descriptor

  Add Government and Non-Government documents related to this Spec in this section.

  Add to the tables between the |==== tags, below the header line

  Example:
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Document Number or Descriptor|Document Title                <-- header line
                                                   <-- empty line for readability (optional)
    |NPR 2810.1|Security of Information Technology <--
    |NASA-SPEC-0000|Super Special NASA Doc         <--
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag


 NOTE: Be sure to make all document titles links to those documents. 

 NOTE: Comment out the Non-Government Documents table if you do not have any documents to include.  (i.e., Do not leave a blank table in the document)
////

== Applicable Documents

=== General

The documents listed in this section were used as references during the creation of this Specification. These documents can serve as additional support for ISOs in meeting the requirements of this Security Configuration Specification. 

=== Government Documents

[%header, cols=2*a]
|===
|Document Number or Descriptor|Document Title

|NASA-STD-2601|_Security Requirements for Computing Devices_
|NPR 2810.1x|_Security of Information Technology_
|===

=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Number or Descriptor|Document Title

|===

////
ACRONYMS AND DEFINITIONS:

  The following tables should be in alphabetical order

  Note they do not have a header line, so content can be added in order.

  Add to the tables between the |==== tags

  Example:
    .Definitions                                   <-- table title (will display in presentation)
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Space|Is really, really big                   <-- term and definition/acronym and expansion
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag

////

== Acronyms and Definitions

.Acronyms and Abbreviations
[%header,width="100%",cols="1,3"]
|====
|Term|Expanded

|AO|Authorizing Official
|ACL|Assessed and Cleared List for technology procurement
|ASCS|Agency Security Configuration Standards
|CDM|Continuous Diagnostics and Mitigation
|CIO|Chief Information Officer
|CIS|Center for Internet Security
|CSET|Cybersecurity Standards and Engineering Team
|CSPP|Cybersecurity and Privacy Program
|DAR|Data At Rest
|DISA|Defense Information Systems Agency
|FFRDC|Federally Funded Research and Development Center
|FISMA|Federal Information Security Modernization Act
|FPKI|Federal Public Key Infrastructure
|GRC|Glenn Research Center
|ICAM|Identity, Credential, and Access Management
|IDI|ICAM Device Integration
|ISO|Information System Owner
|JPL|Jet Propulsion Laboratory
|NASA|National Aeronautics and Space Administration
|NCTR|NASA Client Trust Reference
|NIST|National Institute of Standards and Technology
|NPR|NASA Procedural Requirement
|NSA|National Security Agency
|NTAM|NASA Trust Anchor Management
|NTSP|NASA Technical Standards Panel
|OCIO|Office of the Chief Information Officer
|PIV|Personal Identity Verification
|PKI|Public Key Infrastructure
|RBD|Risk-Based Decision
|RISCS|Risk Information and Security Compliance System
|SAISO|Senior Agency Information Security Officer
|SOC|Security Operations Center
|STIG|Security Technical Implementation Guide

|====



////
DEFINITIONS TABLE:
 Comment out this table if you have no definitions to add. 
  Do not leave a blank table in the document.
////

.Definitions
[%header,width="100%",cols=2*a]
|====
|Term |Definition

| |
|====



////
VERSION AND LIFECYCLE:

 In the description below the "Version and Lifecycle" heading, there are 2 instances where 
 "(operating system / application)" appears. 
  NOTE: Spec authors must edit this manually to suit what you are writing the Spec for. 
////

== Version and Lifecycle

This Specification applies to the (operating system / application) defined in the chart below, as well as to any more recent version(s) of this (operating system/ application).


////
All fields in this table should be automatically populated from the Document Variables  
////

[cols="25%h,75%"]
|====
ifeval::[ "{function}" != "" ]
|Function
|{function}
endif::[]
ifeval::[ "{application}" != "" ]
|Application
|{application}
endif::[]
ifeval::[ "{minversion}" != "" ]
|Minimum Version
|{minversion}
endif::[]
ifeval::[ "{removaldate}" != "" ]
|Required Removal Date
|{removaldate}
endif::[]

|====


== Security Configurations
 
////
CRITICAL SETTINGS REFERENCE:
 NOTE: This section has been commented out, as it will be applicable to a minority of Specifications. 

       If the Specification you are writing DOES include Critical Settings, be sure to move the bottom of this comment block up to allow the section to be visible.


CRITICAL SETTINGS TABLE: 
 Critical settings should be listed in this table in the same order that they appear in the document.

 In the left column, fill in the ASCS number for each setting.

 In the right column, write the ASCS control title (as it appears in the ToC)

 Link each ASCS number in the left hand column to the full setting explanation in document.


=== Critical Settings Reference

The table below provides a quick view of the security configuration settings that are classified as *critical*. All configurations that are classified as *critical* _SHALL NOT_ be eligible for any modifications through the application of a risk based decision (RBD). The *critical* settings in the table are linked to a detailed explanation of the configuration setting in the subsequent section of this Specification.

[cols="1h,1"]
|===
| ASCS Number | ASCS Control Title
| ascs #| critical setting 1
| ascs # | critical setting 2
|===

////


=== Required Settings

This section contains all settings *required* for Agency compliance, as well as a detailed description for each setting. Required controls are monitored, scored, and reported by the Agency. 

Settings that are classified as *required* _MAY_, in limited and justified instances, be amended through the proper application of an RBD. To pursue an RBD, see section 1.4, Tailoring, of this Specification.


////
RECOMMENDED SETTINGS REFERENCE:
 NOTE: This section has been commented out, as it will be applicable to a minority of Specifications. 
 
      If the Specification you are writing DOES include Recommended Settings, be sure move the bottom of this comment block up to allow the section to be visible.


=== Recommended Settings

This section contains all *recommended* settings. Settings that are classified as *recommended* are not required, but they are deemed highly beneficial by ASCS. These settings are expected to be implemented, unless there is a justifiable cause not to. However, *recommended* settings that are not implemented will not be scored as deviation from compliance.
////


////
GENERAL OPERATIONAL GUIDANCE:
 NOTE: This section has been commented out, as it will be applicable to a minority of Specifications. 
 
       If the Specification you are writing DOES include General Operational Guidance, be sure move the bottom of this comment block up to allow the section to be visible.

== General Operational Guidance
  (Input Content as needed).

////


////
APPENDIX SECTION
  Appendices are numbered differently then the rest of the document, so make sure to use 3 or more markers on subsection
    titles (=== SUBSECTION). If you drop to 2 markers (==) it will start normal numbering again.
  Content of the appendix will format for sections and subsections, but not number them.
  
  It is appropriate to continue using heading tags (===) as normal.
  
  Appendices will be lettered based on the [appendix] tag, so the example title will appear as
   APPENDIX A: TITLE OF APPENDIX

  Additional appendices can be used by the [appendix] tag immediately followed on the next line with a
    2 marker title (== APPENDIX TITLE). following appendix will use appropriate letters (B, C, D...)
////

[appendix]
== TITLE OF APPENDIX
