= Security Configuration Specification Name
:doctype: book
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:
// Title Page Variables
:document-type: NASA TECHNICAL SPECIFICATION
:document-identifier: NASA-SPEC-2XXXX
:document-title: DOCUMENT TITLE
:document-subtitle: SECURITY CONFIGURATION SPECIFICATION
:approved-date: 20XX-XX-XX
// document process versions: "Initial Draft", "Informal Draft", "Formal Draft", "Final Draft", "Baseline"
:version: Initial Draft
:revision-date: 20XX-XX-XX
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
:superseding-document: NASA-SPEC-2XXX
:superseding-document-revision: XXXX


// Do not show the footer for HTML
ifdef::backend-html5[]
:nofooter:
endif::[]

// An additional title is needed for PDF output
ifdef::backend-pdf[]
[colophon]
= {nbsp}
endif::[]

// Title Page
include::document_basecamp/title_page.adoc[]

toc::[]

[dedication]
== Document History Log

[%header,width="100%",cols="1,1,1,2,4"]
|====
|Status
|Document Revision
|Change Number
|Approval Date
|Description

|Baseline
|1.0
|
|{approved-date}
|

|====

<<<

== Foreword

This Technical Standard is approved for use by NASA Headquarters and all NASA Centers. It is intended to provide common guidance for (provide one or two sentences that will be similar to unique Purpose content).

Adherence to this Standard ensures compliance with (fill in sentence and reference NASA or other Federal policy, standard, or specification subject matter — this may be specific to formal documents, or simply general subject matter).

Requests for information, corrections, or additions to this Specification should be directed to the John H. Glenn Research Center at Lewis Field (GRC), Enterprise Technology Assessments and Digital Standards (ETADS) Office, MS 142-5, Cleveland, OH, 44135 or to nasa-ascs-staff@lists.nasa.gov.

+++<br><br><br><br><br><br><br>+++


Michael Witt +
Senior Agency Information Security Officer

////
COMMON CONTENT
  This is the point at which document numbering starts.
  Modification of this section should be fairly common, but not extensive.
  Look for the DOCUMENT CONTENT comment section for the expected place for the body of the work
////

:numbered:

== Scope

=== Purpose

The purpose of this NASA Technical Standard is (add one-to-two sentence description).

=== Applicability

This Standard is applicable to technology programs and projects managed by federal employee or contractor Information System Owners (ISOs) at NASA Headquarters and NASA Centers, including Component Facilities and Technical and Service Support Centers. This Standard applies to the Jet Propulsion Laboratory (JPL), a Federally Funded Research and Development Center (FFRDC), and other non-Agency facility contractors only to the extent specified or referenced in applicable contracts.

NPR 2810.1x, Security of Information Technology, clearly defines the role and responsibilities of information system owners (ISO) in relation to Agency information systems. These responsibilities include:

- Acquiring, developing, integrating, operating, modifying, and maintaining information systems.
- Ensuring system-level implementation of all Agency and Center requirements.
- Taking appropriate actions to identify and minimize or eliminate information system security deficiencies and weaknesses.

Standard guidance will be added, replaced, or removed as appropriate to align these responsibilities with Agency information security- and privacy-related program and project requirements.

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized Enterprise Technology Assessments and Digital Standards (ETADS) within the ETADS Charter, §2, to create binding Technical Standards related to Agency security topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes ETADS as a standards-developing organization within the Agency. NTSP provides access to all technical standards at:

https://standards.nasa.gov/

=== Tailoring

Tailoring of this NASA Technical Standard for application to a specific program, project, or system shall be formally documented as part of program or project requirements and approved by the responsible Information System Owner and Authorizing Official.

== Applicable Documents

=== General

The documents listed in this section contain provisions that constitute requirements of this NASA Technical Specification as cited in the text.

The latest issuances of cited documents shall apply unless specific versions are designated.

Non-use of specifically designated versions shall be approved by the responsible Technical Authority.

The applicable documents are accessible at https://standards.nasa.gov or may be obtained directly from the Standards Developing Body or other document distributors.

=== Government Documents

////
ASSOCIATED DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  Add to the tables between the |==== tags, below the header line 
  Example: 
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Document Number|Document Title                <-- header line
                                                   <-- empty line for readability (optional)
    |NPR 2810.1|Security of Information Technology <-- 
    |NASA-SPEC-0000|Super Special NASA Doc         <-- 
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag
////

[%header, cols=2*a]
|===
|Document Number|Document Title

|===

=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Number|Document Title

|===

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  The following tables should be in alphabetical order
  Note they do not have a header line, so content can be added in order.
  Add to the tables between the |==== tags
  Example: 
    .Definitions                                   <-- table title (will display in presentation)
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Space|Is really, really big                   <-- term and definition/acronym and expansion
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag
////

== Acronyms and Definitions

.Acronyms and Abbreviations
[width="100%",cols="1,3"]
|====
|NASA|National Aeronautics and Space Administration

|====

.Definitions
[width="100%",cols="1,3"]
|====
||

|====

////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4. 
  Each section beyond this (notated by ==) will increment.
////

== DOCUMENT BODY WHICH STARTS AT SECTION 4

Content 



////
APPENDIX SECTION
  Appendix number differently then the document, so make sure to use 3 or more morkers on subsection
    titles (=== SUBSECTION). If you drop to 2 markers (==) it will start normal numbering again.
  Content of the appendix will format for sections and subsection, but not number them. 
  It is appropriate to continue using heading tags (===) as normal.
  Appendix will be lettered based on the [appendix] tag, so the example title will appear as

  APPENDIX A: TITLE OF APPENDIX

  Additional appendix can be used by the [appendix] tag immediately followed on the next line with a 
    2 marker title (== APPENDIX TITLE). following appendix will use appropriate letters (B, C, D...)
////

[appendix]
== TITLE OF APPENDIX

