= Security Configuration Specification Name
:doctype: book
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:noheader:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:
// Title Page Variables
:measurement-system: NOT MEASUREMENT SENSITIVE
:document-type: NASA TECHNICAL SPECIFICATION
:document-identifier: NASA-SPEC-2XXXX
:document-title: DOCUMENT TITLE
:document-subtitle: SECURITY CONFIGURATION SPECIFICATION
:approved-date: 20XX-XX-XX
:version: v1.X
:revision-date: 20XX-XX-XX
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
:superseding-document: NASA-SPEC-2XXX
:superseding-document-revision: XXXX


// Do not show the footer for HTML
ifdef::backend-html5[]
:nofooter:
endif::[]

// An additional title is needed for PDF output
ifdef::backend-pdf[]
[colophon]
= {nbsp}
endif::[]

// Title Page
include::document_basecamp/scs/title_page.adoc[]

toc::[]

[dedication]
== DOCUMENT HISTORY LOG

[%header,width="100%",cols="1,1,1,2,4"]
|====
|Status
|Document Revision
|Change Number
|Approval Date
|Description

|Baseline
|1.0
|
|{approved-date}
|

|====

<<<

== FOREWORD

This NASA Technical Specification is published by the National Aeronautics and Space Administration (NASA) to describe technical requirements for purchased or in-house items, services, functions, or processes for NASA programs and projects.

This NASA Technical Specification is approved for use by NASA Headquarters and NASA Centers and Facilities and may be cited in contract, program, and other Agency documents as a technical requirement. It may also apply to the Jet Propulsion Laboratory and other contractors only to the extent specified or referenced in applicable contracts.

This NASA Technical Specification establishes common guidance for FILL IN GUIDANCE.

Requests for information, corrections, or additions to this Specification should be directed to the John H. Glenn Research Center at Lewis Field (GRC), Enterprise Technology Assessments and Digital Standards (ETADS) Office, MS 142-5, Cleveland, OH, 44135 or to nasa-ascs-staff@lists.nasa.gov.

+++<br><br><br><br><br><br><br>+++


Michael Witt +
Senoir Agency Information Security Officer


:numbered:
== Scope

=== Purpose

This document provides FILL IN PURPOSE.

=== Applicability

This NASA Technical Specification is approved for use by NASA Headquarters and NASA Centers and Facilities and may be cited in contract, program, and other Agency documents as a technical requirement. It may also apply to the Jet Propulsion Laboratory and other contractors only to the extent specified or referenced in applicable contracts.

IMPORTANT: “Shall”, “Must”, and “Required” statements in this document impose an obligation to act. “Shall not” statements generally prohibit an action. “Should” statements imply an obligation to act, but not a necessity. “May” and “Optional” statements denote actions that are acceptable and optional for system owners to take.

WARNING: This document contains cautionary statements. Implementors should read and heed these statements prior to altering configurations.

== Applicable Documents

=== General

The documents listed in this section contain provisions that constitute requirements of this NASA Technical Specification as cited in the text.

The latest issuances of cited documents shall apply unless specific versions are designated.

Non-use of specifically designated versions shall be approved by the responsible Technical Authority.

The applicable documents are accessible at https://standards.nasa.gov or may be obtained directly from the Standards Developing Body or other document distributors.

=== Government Documents

[%header, cols=2*a]
.National Aeronautics and Space Administration (NASA)
|===

|Document Number
|Document Title

|NPR 2810.1
|Security of Information Technology

|===

=== Non-Government Documents

[%header, cols=2*a]
.Center for Internet Security (CIS)
|===

|Document Number
|Document Title

|Benchmark
|Example

|===