:doctype: book
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:
// Title Page Variables
:measurement-system: ENTERPRISE IT INFRASTRUCTURE GUIDANCE
:document-type: NASA TECHNICAL SPECIFICATION
:document-identifier: NASA-SPEC-2XXXX
:document-title: DOCUMENT TITLE
:document-subtitle: SECURITY CONFIGURATION SPECIFICATION
:approved-date: 20XX-XX-XX
// document process versions: "Initial Draft", "Informal Draft", "Formal Draft", "Final Draft", "Baseline"
:version: Initial Draft
:revision-date: 20XX-XX-XX
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
:superseding-document: NASA-SPEC-2XXX
:superseding-document-revision: XXXX
////
TABLE CONTENT
Similar to the CRC table in NASA-STD-2804.  Fill out these fields to complete the table.
Description of fields:
function: Applicaiton function 
application: Application name
relevanttechnicalstandard: Relevant Technical Standard.  i.e. NASA-STD-2601, Section 5.7., NASA document, STIG, NIST, etc.
requiredsettings: Additional required settings, if needed
version: Minimum application version required
comments: Additional comments
removaldate: Required removal date from the enviornment
////
// Table content
:function:  
:application:  
:relevanttechnicalstandard:  
:requiredsettings:  
:minversion: 
:comments: 
:removaldate:  

= {application} Security Configuration Specification

// Do not show the footer for HTML
ifdef::backend-html5[]
:nofooter:
endif::[]

// An additional title is needed for PDF output
ifdef::backend-pdf[]
[colophon]
= {nbsp}
endif::[]

// Title Page
include::document_basecamp/title_page.adoc[]

toc::[]

[dedication]
== Document History Log

[%header,width="100%",cols="1,1,1,2,4"]
|====
|Status
|Document Revision
|Change Number
|Approval Date
|Description

|Baseline
|1.0
|
|{approved-date}
|

|====

<<<

== Foreword

This Technical Standard is approved for use by NASA Headquarters and all NASA Centers. It is intended to provide common guidance for minimum security requirements for {application}.

Adherence to this Standard ensures compliance with NASA-STD-2601, which defines operating system and application security requirements that must be implemented on NASA information systems.

Requests for information, corrections, or additions to this Specification should be directed to the John H. Glenn Research Center at Lewis Field (GRC), Enterprise Technology Assessments and Digital Standards (ETADS) Office, MS 142-5, Cleveland, OH, 44135 or to nasa-ascs-staff@lists.nasa.gov.

+++<br><br><br><br><br><br><br>+++


Michael Witt +
Senior Agency Information Security Officer

////
COMMON CONTENT
  This is the point at which document numbering starts.
  Modification of this section should be fairly common, but not extensive.
  Look for the DOCUMENT CONTENT comment section for the expected place for the body of the work
////

:numbered:

== Scope

=== Purpose

The purpose of this NASA Technical Standard is to provide mandatory version and configuration guidance for {application} deployment and operation.

=== Applicability

This Standard is applicable to technology programs and projects managed by federal employee or contractor Information System Owners (ISOs) at NASA Headquarters and NASA Centers, including Component Facilities and Technical and Service Support Centers. This Standard applies to the Jet Propulsion Laboratory (JPL), a Federally Funded Research and Development Center (FFRDC), and other non-Agency facility contractors only to the extent specified or referenced in applicable contracts.

NPR 2810.1x, _Security of Information Technology_, clearly defines the role and responsibilities of ISOs in relation to Agency information systems. These responsibilities include:

- Acquiring, developing, integrating, operating, modifying, and maintaining information systems.
- Ensuring system-level implementation of all Agency and Center requirements.
- Taking appropriate actions to identify and minimize or eliminate information system security deficiencies and weaknesses.

Standard guidance will be added, replaced, or removed as appropriate to align these responsibilities with Agency information security- and privacy-related program and project requirements.

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized Enterprise Technology Assessments and Digital Standards (ETADS) within the link:https://etads.nasa.gov/charter[ETADS Charter], ยง2, to create binding Technical Standards related to Agency security topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes ETADS as a standards-developing organization within the Agency. NTSP provides access to all technical standards at:

https://standards.nasa.gov/

=== Tailoring

Tailoring of this NASA Technical Standard for application to a specific program, project, or system shall be formally documented as part of program or project requirements and approved by the responsible ISO and Authorizing Official (AO).

== Applicable Documents

=== General

The documents listed in this section support requirements of this NASA Technical Standard, as cited in the text. Use of other guidance in system implementations shall be documented by the ISO and approved by an AO.

The applicable documents are accessible at https://nodis3.gsfc.nasa.gov/ or https://standards.nasa.gov, or may be obtained directly from the standards developing body or other document distributors.

=== Government Documents

////
ASSOCIATED DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  Add to the tables between the |==== tags, below the header line 
  Example: 
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Document Number|Document Title                <-- header line
                                                   <-- empty line for readability (optional)
    |NPR 2810.1|Security of Information Technology <-- 
    |NASA-SPEC-0000|Super Special NASA Doc         <-- 
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag
////

[%header, cols=2*a]
.National Aeronautics and Space Administration (NASA)
|===
|Document Number|Document Title

|NASA-STD-2601|_Security Requirements for Computing Devices_

|NPR 2810.1x|_Security of Information Technology_

|===

=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Number|Document Title

|===

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  The following tables should be in alphabetical order
  Note they do not have a header line, so content can be added in order.
  Add to the tables between the |==== tags
  Example: 
    .Definitions                                   <-- table title (will display in presentation)
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Space|Is really, really big                   <-- term and definition/acronym and expansion
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag
////

== Acronyms and Definitions

.Acronyms and Abbreviations
[width="100%",cols="1,3"]
|====
|AO|Authorizing Official
|ACL|Approved and Cleared List for technology procurement
|ASCS|Agency Security Configuration Standards
|CDM|Continuous Diagnostics and Monitoring
|CIO|Chief Information Officer
|CIS|Center for Internet Security
|DAR|Data At Rest
|DISA|Defense Information Systems Agency
|ETADS|Enterprise Technology Assessments and Digital Standards
|FFRDC|Federally Funded Research and Development Center
|FISMA|Federal Information Security Modernization Act
|FPKI|Federal Public Key Infrastructure
|ICAM|Identity, Credential, and Access Management
|IDI|ICAM Device Integration
|ISO|Information System Owner
|JPL|Jet Propulsion Laboratory
|NCTR|NASA Client Trust Reference
|NIST|National Institute of Standards and Technology
|NPR|NASA Procedural Requirement
|NSA|National Security Agency
|NTAM|NASA Trust Anchor Management
|NTSP|NASA Technical Standards Panel
|OCIO|Office of the Chief Information Officer
|PIV|Personal Identity Verification
|PKI|Public Key Infrastructure
|RISCS|Risk Information and Security Compliance System
|SAISO|Senior Agency Information Security Officer
|SOC|Security Operations Center
|STIG|Security Technical Implementation Guide

|====

.Definitions
[width="100%",cols="1,3"]
|====
||

|====

////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4. 
  Each section beyond this (notated by ==) will increment.
////

== Minimum Security Requirements

[cols="25%h,75%"]
|====
|Function
|{function}
|Application
|{application}
|Relevant Technical Standard
|{relevanttechnicalstandard}
|Required Settings
|{requiredsettings}
|Minimum Version
|{minversion}
|Comments
|{comments}
|Required Removal Date
|{removaldate}

|====




