:doctype: book
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:

// Title Page Variables
:document-type: NASA TECHNICAL SPECIFICATION
:document-identifier: NASA-SPEC-2XXXX
// document version: e.g., 1.0, 1.1, 2.0 etc.
:document version: vx.x
// document-title: If using acronyms in title, check with Sean for approval.  USE ALL CAPS
:document-title: DOCUMENT TITLE
:document-subtitle: NASA TECHNICAL SPECIFICATION
// approved-date: Input the approved date only when signed. Delete the 20XX-XX-XX and leave blank until it is signed. 
:approved-date: 20XX-XX-XX
// document-stage: Input either "Draft" or "Baseline"
:document-stage: Draft
// comment block out the cover-page-marks before publishing
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
// superseding-document: delete and leave blank if N/A
:superseding-document: NASA-SPEC-2XXX
// superseding-document-revision: delete and leave blank if N/A
:superseding-document-revision: v.XXXX
// xrefstyle full shows the section number and title
:xrefstyle: full

////
DOCUMENT VARIABLES:
 Description of fields:
  function:     Application function (e.g., web browser, media player, etc.)
  application:  The name of the OS or Application 
  specificationtype: Enter either "operating system" or "application"
  minversion:   Minimum application version required
  removaldate:  Required removal date from the environment

////

// Document variables:
:function:
:application:
:specificationtype:
:minversion:
:removaldate:

= {application} NASA Technical Specification

// Do not show the footer for HTML
ifdef::backend-html5[]
:nofooter:
endif::[]

// An additional title is needed for PDF output
ifdef::backend-pdf[]
[colophon]
= {nbsp}
endif::[]

// Title Page
include::document_basecamp/title_page.adoc[]

toc::[]


////
DOCUMENT HISTORY LOG:
  Newest version at the top of the table!
  Oldest/first version in the bottom row!

  You must add a row to the top of the table each time a new version of the Spec is published.
 
  Track drafts and include descriptions for each draft while the document is out for review. 
  But be sure to DELETE  draft tracking and update the approved date when it is signed and ready to be published. 

  The description box must not be left blank, but it should be brief. 
  Example descriptions: 
    "Baseline", "Updates based on DEFEND AWARE", "Small DNS over HTTP update"

NOTE: 
 Approval Date:  this will automatically be pulled from the VARIABLES at the top. 
 If you are writing an updated version of a Spec, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Approval Date
|Description

|1.0
|{approved-date}
|
|====

<<<

////
FOREWORD:
 Note that this template is worded to best suit Specs that fall under Standard 2601.

 If your spec does not fall under Standard 2601 - make sure to edit paragraph 3 so that it is accurate for your spec. 
////

== Foreword

This NASA Technical Specification is published by the National Aeronautics and Space Administration (NASA) to describe technical requirements for purchased or in-house items, services, functions, or processes for NASA programs and projects.

This NASA Technical Specification is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other Agency documents. It may also apply to the Jet Propulsion Laboratory (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

Adherence to this NASA Technical Specification ensures compliance with NASA-STD-2601, _Minimum Cybersecurity Requirements for Computing Systems_, which defines operating system and application security requirements that must be implemented on NASA information systems. This Specification provides the enforceable, measurable details of NASA-STD-2601.

Requests for information, corrections, or additions to this Specification can be made via the "Contact ASCS" form, found here: https://cset.nasa.gov/ascs/requests/.   


+++<br><br><br><br>+++


Michael Witt 
+++<br><br>+++
Senior Agency Information Security Officer

+++<br>+++

////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.
  
  Please be sure to read comment blocks for instructions. 
////

:numbered:

////
SCOPE:
 The name of the OS or App will be automatically input as long as you have properly filled in the Document Variables section at the top of this Spec. 

 If your Spec is not a configuration Spec, you may also need to rewrite the Purpose and Applicability sections to fit your Spec. - Please read the comment blocks above each subheading. 
////

== Scope

////
Purpose: 
 If your spec does not fall under Standard 2601/ is not a configuration Spec:
   Make sure to edit the Purpose so that it is accurate for your spec. 
////

=== Purpose

The purpose of this NASA Technical Specification is to provide mandatory version and configuration guidance for {application} deployment and operation.

////
Applicability: 
 There are two options for sentence 1 under Applicability - choose the one that applies to your spec to make visible. 
     e.g.:
       SEP is applicable to all computing systems = choose first option.
       An Adobe spec would only be applicable to systems that have Adobe.  = choose second option. 
 
 If your spec does not fall under Standard 2601/ is not a configuration Spec:
   Make sure to edit paragraph 1 under Applicability so that it is accurate for your spec. 
////
=== Applicability

// This NASA Technical Specification is applicable to all computing systems.
// This NASA Technical Specification is applicable to all computing systems using {application}. 

This NASA Technical Specification is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other Agency documents. It may also apply to the Jet Propulsion Laboratory (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.


=== Tailoring

In accordance with NASA-STD-2601, _Minimum Cybersecurity Requirements for Computing Systems_, any and all risk-based decisions (RBDs) to tailor this NASA Technical Specification in order to meet the needs of a specific program, project, or system _SHALL_ be approved by the responsible Information System Owner (ISO) and Authorizing Official (AO) and formally documented by the ISO or system administrators in the  System Security Plan (SSP) under program or project requirements. 

NASA-STD-2601 mandates that the AO _SHALL_ ensure that only systems posing an acceptable level of risk to Agency assets, data, and personnel are approved for production operation and that the ISO _SHALL_ ensure all necessary documentation is produced and maintained. 

Note that some NASA Technical Specifications include configuration settings that are classified as "critical". Settings that are classified as "critical" _SHALL NOT_ be eligible for any modifications through the application of an RBD.

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at: https://standards.nasa.gov/. 

+++<br>+++

////
APPLICABLE DOCUMENTS:

  The tables in this section should be in alpha-numerical order according to Document Number or Descriptor

  Add Government and Non-Government documents related to this Spec in this section.

  Add to the tables between the |==== tags, below the header line

  Example:
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Document Number or Descriptor|Document Title                <-- header line
                                                   <-- empty line for readability (optional)
    |NPR 2810.1|Security of Information Technology <--
    |NASA-SPEC-0000|Super Special NASA Doc         <--
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag


 NOTE: Be sure to make all document titles links (YOURLS) to those documents. 

////

== Applicable Documents

=== General

The documents listed in this section contain provisions that constitute requirements of this NASA Technical Specification. These documents can serve as additional support in meeting the requirements defined in this  Specification. 

=== Government Documents

[%header, cols=2*a]
|===
|Document Number or Descriptor|Document Title

|link:https://cset.nasa.gov/latest/nasa-std-2601[NASA-STD-2601]| _Minimum Cybersecurity Requirements for Computing Systems_ 
|link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1]| _Security of Information Technology_
|===



////
NOTE: Comment out the Non-Government Documents table if you do not have any documents to include.  (i.e., Do not leave a blank table in the document)
////

=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Number or Descriptor|Document Title

|===

+++<br>+++

////
ACRONYMS AND DEFINITIONS:

  The following tables should be in alphabetical order

  Note they do not have a header line, so content can be added in order.

  Add to the tables between the |==== tags

  Example:
    .Definitions                                   <-- table title (will display in presentation)
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Space|Is really, really big                   <-- term and definition/acronym and expansion
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag

////

== Acronyms and Definitions

.Acronyms and Abbreviations
[%header,width="100%",cols="1,3"]
|====
|Term|Expanded

|AO|Authorizing Official
|ASCS|Agency Security Configuration Standards
|CIO|Chief Information Officer
|CSET|Cybersecurity Standards and Engineering Team
|FFRDC|Federally Funded Research and Development Center
|ISO|Information System Owner
|JPL|Jet Propulsion Laboratory
|NASA|National Aeronautics and Space Administration
|NPR|NASA Procedural Requirement
|NTSP|NASA Technical Standards Panel
|OCIO|Office of the Chief Information Officer
|RBD|Risk-Based Decision
|SAISO|Senior Agency Information Security Officer
|SSP|System Security Plan

|====



////
DEFINITIONS TABLE:
  Leave this table comment blocked out if you have no definitions to add, so as not to leave a blank table in the document.
  Remove comment block if necessary.


.Definitions
[%header,width="100%",cols=2*a]
|====
|Term |Definition

| |
|====
////
+++<br>+++

== Version and Lifecycle

This Specification applies to the {specificationtype} defined in the chart below, as well as to any more recent version(s) of this {specificationtype}.


////
All fields in this table should be automatically populated from the Document Variables  
////

[cols="25%h,75%"]
|====
ifeval::[ "{function}" != "" ]
|Function
|{function}
endif::[]
ifeval::[ "{application}" != "" ]
|Application
|{application}
endif::[]
ifeval::[ "{minversion}" != "" ]
|Minimum Version
|{minversion}
endif::[]
ifeval::[ "{removaldate}" != "" ]
|Required Removal Date
|{removaldate}
endif::[]

|====

+++<br>+++

== Security Configurations
 
////
CRITICAL SETTINGS REFERENCE:
 NOTE: This section has been commented out, as it will be applicable to a minority of Specifications. 

       If the Specification you are writing DOES include Critical Settings, be sure to move the bottom of this comment block up to allow the section to be visible.


CRITICAL SETTINGS TABLE: 
 Critical settings should be listed in this table in the same order that they appear in the document.

 In the left column, fill in the ASCS number for each setting.

 In the right column, write the ASCS control title (as it appears in the ToC)

 Link each ASCS number in the left hand column to the full setting explanation in document.


=== Critical Settings Reference

The table below provides a quick view of the security configuration settings that are classified as *critical*. All configurations that are classified as *critical* _SHALL NOT_ be eligible for any modifications through the application of an RBD. The *critical* settings in the table are linked to a detailed explanation of the configuration setting in the subsequent section of this Specification.

[cols="1h,1"]
|===
| ASCS Number | ASCS Control Title
| ascs #| critical setting 1
| ascs # | critical setting 2
|===

////


=== Required Settings

This section contains all settings *required* for Agency compliance, as well as a detailed description for each setting. *Required* controls are monitored, scored, and reported by the Agency. 

Settings that are classified as *required* _MAY_, in limited and justified instances, be amended through the proper application of an RBD. To pursue an RBD, see section 1.3, Tailoring, of this Specification.


////
RECOMMENDED SETTINGS REFERENCE:
 NOTE: This section has been commented out, as it will be applicable to a minority of Specifications. 
 
      If the Specification you are writing DOES include Recommended Settings, be sure move the bottom of this comment block up to allow the section to be visible.


=== Recommended Settings

This section contains all *recommended* settings. Settings that are classified as *recommended* are not required, but they are deemed highly beneficial by ASCS. These settings are expected to be implemented, unless there is a justifiable cause not to. However, *recommended* settings that are not implemented will not be scored as deviation from compliance.
////


////
GENERAL OPERATIONAL GUIDANCE:
 NOTE: This section has been commented out, as it will be applicable to a minority of Specifications. 
 
       If the Specification you are writing DOES include General Operational Guidance, be sure move the bottom of this comment block up to allow the section to be visible.

== General Operational Guidance
  (Input Content as needed).

////

+++<br>+++

////
APPENDIX SECTION
 Note:
   Appendix is commented out - move the comment block if applicable. 

  Appendices are numbered differently then the rest of the document, so make sure to use 3 or more markers on subsection
    titles (=== SUBSECTION). If you drop to 2 markers (==) it will start normal numbering again.
  Content of the appendix will format for sections and subsections, but not number them.
  
  It is appropriate to continue using heading tags (===) as normal.
  
  Appendices will be lettered based on the [appendix] tag, so the example title will appear as
   APPENDIX A: TITLE OF APPENDIX

  Additional appendices can be used by the [appendix] tag immediately followed on the next line with a
    2 marker title (== APPENDIX TITLE). following appendix will use appropriate letters (B, C, D...)


[appendix]
== TITLE OF APPENDIX

////