= Standard Name
:doctype: book
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
:toc: macro
:toc-title: TABLE OF CONTENTS
:toclevels: 3
:toc-placement!:
// Title Page Variables
:document-type: NASA TECHNICAL STANDARD
:document-identifier: NASA-STD-XXXX
// document-title: No acronyms in title - spell them out
:document-title: DOCUMENT TITLE
:document-subtitle: TECHNICAL STANDARD
// approved-date: input the approved date only when signed (NOTE: this variable will automatically be plugged into the document history log)
:approved-date: 20XX-XX-XX
// version: "Initial Draft", "Informal Draft", "Formal Draft", "Final Draft", "Baseline"
:version: Initial Draft
:revision-date: 20XX-XX-XX
// comment block out the cover-page-marks before publishing
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
:superseding-document: NASA-STD-XXXX
:superseding-document-revision: XXXX
:signatory: First Name Last Name
:signatory-title: Signatory's Position/Title


// Do not show the footer for HTML
ifdef::backend-html5[]
:nofooter:
endif::[]

// An additional title is needed for PDF output
ifdef::backend-pdf[]
[colophon]
= {nbsp}
endif::[]

// Title Page
include::document_basecamp/title_page.adoc[]

[dedication]
== Document History Log

////
DOCUMENT HISTORY LOG:
  Newest version at the top of the table!
  Oldest/first version in the bottom row!

  You must add a row to the top of the table each time a new version of the Standard is published.
 
  DO NOT TRACK DRAFTS (informal draft, formal draft, etc.) in the Document History table!
    Only update this table to include signed and published versions. 

  The description box must not be left blank, but it should be brief. 
   Example descriptions: 
    "Baseline", "Updates based on ___"


NOTE: 
 Approval Date:  this will automatically be pulled from the VARIABLES at the top. 
 If you are writing an updated version of a Standard, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////


[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Approval Date
|Description

|Baseline
|{approved-date}
|

|====

////
Forward:
 Authors need to be sure to insert text to complete the statement in the third paragraph of the Forward. 
////

== Foreword

This NASA Technical Standard is published by the National Aeronautics and Space Administration (NASA) to provide uniform engineering and technical requirements for processes, procedures, practices, and methods that have been endorsed as standard for NASA programs and projects, including requirements for selection, application, and design criteria of an item.

This NASA Technical Standard is approved for use by NASA Headquarters and NASA Centers, including Component Facilities and Technical and Service Support Centers.

This NASA Technical Standard establishes (provide one or two sentences that will be similar to unique Purpose content).

Requests for information, corrections, or additions to this NASA Technical Standards should be directed to the NASA John H. Glenn Research Center at Lewis Field (GRC), Cybersecurity Standards and Engineering Team (CSET), MS 142-5, Cleveland, OH, 44135, or to standards-comments@lists.nasa.gov.

+++<br><br><br><br><br><br><br>+++


{signatory} +
{signatory-title}

+++<br><br><br><br><br><br><br>+++

toc::[]

////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.

  Please be sure to read comment blocks for instructions. 
////

:numbered:

== Scope

////
Purpose:
 Authors need to be sure to insert text to complete the statement of purpose for this Standard.
////

=== Purpose

The purpose of this NASA Technical Standard is (add one-to-two sentence description).

=== Applicability

This NASA Technical Standard is applicable to technology programs and projects managed by federal employee or contractor Information System Owners (ISOs) at NASA Headquarters and NASA Centers, including Component Facilities and Technical and Service Support Centers. This Standard applies to the Jet Propulsion Laboratory (JPL), a Federally Funded Research and Development Center (FFRDC), and other non-Agency facility contractors only to the extent specified or referenced in applicable contracts.

NPR 2810.1x, _Security of Information Technology_, clearly defines the role and responsibilities of ISOs in relation to Agency information systems. These responsibilities include:

* acquiring, developing, integrating, operating, modifying, and maintaining information systems;
* ensuring system-level implementation of all Agency and Center requirements; and
*	taking appropriate actions to identify and minimize or eliminate information system security deficiencies and weaknesses.

ISO responsibilities will be added, replaced, or removed from NPR 2810.1x when such changes are deemed appropriate by the Cybersecurity and Privacy Program (CSPP) in order to align these responsibilities with Agency information security- and privacy-related program and project requirements.

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at: https://standards.nasa.gov/


=== Tailoring

Tailoring of this NASA Technical Standard for application to a specific program, project, or system shall be formally documented as part of program or project requirements and approved by the responsible ISO and Authorizing Official (AO).


////
APPLICABLE DOCUMENTS:

 The following tables should be in alpha-numerical order according to Document Number or Descriptor

  Add Government and Non-Government documents related to this Spec in this section.

  Add to the tables between the |==== tags, below the header line

  Example:
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Document Number or Descriptor|Document Title                <-- header line
                                                   <-- empty line for readability (optional)
    |NPR 2810.1|Security of Information Technology <--
    |NASA-SPEC-0000|Super Special NASA Doc         <--
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag


NOTE: Be sure to make all document titles links to those documents. 

NOTE: Comment out the Non-Government Documents table if you do not have any documents to include. 
 (i.e., Do not leave a blank table in the document)

////

== Applicable Documents

=== General

The documents listed in this section were used as references during the creation of this Standard. These documents can serve as additional support for users in meeting the requirements of this Technical Standard . 


=== Government Documents

[%header, cols=2*a]
|===
|Document Number|Document Title

|===


=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Number|Document Title
|===

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  The following tables should be in alphabetical order
  Note they do not have a header line, so content can be added in order.
  Add to the tables between the |==== tags
  Example:
    .Definitions                                   <-- table title (will display in presentation)
    [%header, cols=2*a]                            <-- table format block
    |====                                          <-- table opening tag
    |Space|Is really, really big                   <-- term and definition/acronym and expansion
                                                   <-- empty line for readability (optional)
    |====                                          <-- table closing tag
////

== Acronyms and Definitions

.Acronyms and Abbreviations
[width="100%",cols="1,3"]
|====
|AO|Authorizing Official
|ACL|Assessed and Cleared List for technology procurement
|ASCS|Agency Security Configuration Standards
|CDM|Continuous Diagnostics and Mitigation
|CIO|Chief Information Officer
|CIS|Center for Internet Security
|CSET|Cybersecurity Standards and Engineering Team
|DAR|Data At Rest
|DISA|Defense Information Systems Agency
|FFRDC|Federally Funded Research and Development Center
|FISMA|Federal Information Security Modernization Act
|FPKI|Federal Public Key Infrastructure
|ICAM|Identity, Credential, and Access Management
|IDI|ICAM Device Integration
|ISO|Information System Owner
|JPL|Jet Propulsion Laboratory
|NCTR|NASA Client Trust Reference
|NIST|National Institute of Standards and Technology
|NPR|NASA Procedural Requirement
|NSA|National Security Agency
|NTAM|NASA Trust Anchor Management
|NTSP|NASA Technical Standards Panel
|OCIO|Office of the Chief Information Officer
|PIV|Personal Identity Verification
|PKI|Public Key Infrastructure
|RISCS|Risk Information and Security Compliance System
|SAISO|Senior Agency Information Security Officer
|SOC|Security Operations Center
|STIG|Security Technical Implementation Guide

|====

.Definitions
[width="100%",cols="1,3"]
|====
||

|====

////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4.
  Each section beyond this (notated by ==) will increment.
////

== DOCUMENT BODY WHICH STARTS AT SECTION 4

Content


////
APPENDIX SECTION
  Appendices are numbered differently then the rest of the document, so make sure to use 3 or more markers on subsection
    titles (=== SUBSECTION). If you drop to 2 markers (==) it will start normal numbering again.
  Content of the appendix will format for sections and subsections, but not number them.
  
  It is appropriate to continue using heading tags (===) as normal.
  
  Appendices will be lettered based on the [appendix] tag, so the example title will appear as
   APPENDIX A: TITLE OF APPENDIX

  Additional appendices can be used by the [appendix] tag immediately followed on the next line with a
    2 marker title (== APPENDIX TITLE). following appendix will use appropriate letters (B, C, D...)
////

[appendix]
== TITLE OF APPENDIX
