:doctype: book
ifdef::backend-pdf[]
:front-cover-image: image::build/pdf-cover.pdf[]
endif::[]
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
ifdef::backend-html5[]
:toc: macro
:toc-placement!:
endif::[]
:toc-title: TABLE OF CONTENTS
:toclevels: 3
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

// NOTE: include statement need blank line before and after

include::document-variables.adoc[]

:noheader:
:nofooter:

ifdef::backend-pdf[]
= NASA STANDARD {document-identifier}
{document-subtitle}
:toc: preamble
endif::[]

ifdef::backend-html5[]
= NASA STANDARD {document-identifier}

// NOTE: include statement need blank line before and after

include::document_basecamp/title_page.adoc[]

toc::[]

endif::[]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row! 
  Oldest/first version in the bottom row!

  You must *add a row to the top of the table* each time a new version of the Standard is published.
 
  Track drafts and include descriptions for each draft while the document is out for review. 

  But be sure to DELETE DRAFT TRACKING and update the approved date when it is signed and ready to be published. 

  The description box must not be left blank, but it should be brief. 
   Example descriptions: "Updated to be applicable to xyz"

   NOTE: 
    Approval Date: this will automatically be pulled from the document-variables.adoc file.

    If you are writing an updated version of a Standard, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log
ifdef::backend-pdf[]
:!nofooter:
endif::[]

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Approval Date
|Description

|1.0
|{approved-date}
|
|====

<<<

////
Forward:
 Authors need to be sure to insert text to complete the statement in the third paragraph of the Foreword. 
////

== Foreword

This NASA Technical Standard is published by the National Aeronautics and Space Administration (NASA) to provide uniform engineering and technical requirements for processes, procedures, practices, and methods that have been endorsed as standard for NASA programs and projects, including requirements for selection, application, and design criteria of an item.

This NASA Technical Standard is approved for use by NASA Headquarters and NASA Centers, including Component Facilities and Technical and Service Support Centers.

This NASA Technical Standard establishes *(COMPLETE THIS SENTENCE WITH A STATEMENT OF PURPOSE FOR THIS STANDARD)*.

Requests for information, corrections, or additions to this Standard can be made via the "Contact ASCS" form, found here: https://cset.nasa.gov/ascs/requests/.


+++<br><br><br><br><br><br><br>+++


{signatory} +
{signatory-title}

+++<br><br><br><br><br><br><br>+++

toc::[]

////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.

  Please be sure to read comment blocks for instructions. 
////

:numbered:

== Scope

////
Purpose:
  Make sure to complete the sentence AND provide more supporting details (if necessary) to describe why this Standard is necessary.

  This section should include more details and explanation as to why this standard has been created than the simple purpose statement in the Foreword. 
////

=== Purpose

The purpose of this NASA Technical Standard is *(COMPLETE THIS SECTION BY EXPLAINING THE PURPOSE OF THIS STANDARD)*.

=== Applicability

This NASA Technical Standard is applicable to technology programs and projects managed by federal employee or contractor Information System Owners (ISOs) at NASA Headquarters and NASA Centers, including Component Facilities and Technical and Service Support Centers. This Standard applies to the Jet Propulsion Laboratory (JPL), a Federally Funded Research and Development Center (FFRDC), and other non-Agency facility contractors only to the extent specified or referenced in applicable contracts.

NPR 2810.1x, _Security of Information Technology_, clearly defines the role and responsibilities of ISOs in relation to Agency information systems. These responsibilities include:

* acquiring, developing, integrating, operating, modifying, and maintaining information systems;
* ensuring system-level implementation of all Agency and Center requirements; and
*	taking appropriate actions to identify and minimize or eliminate information system security deficiencies and weaknesses.

ISO responsibilities will be added, replaced, or removed from NPR 2810.1x when such changes are deemed appropriate by the Cybersecurity and Privacy Program (CSPP) in order to align these responsibilities with Agency information security- and privacy-related program and project requirements.

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at: https://standards.nasa.gov/


=== Tailoring

Tailoring of this NASA Technical Standard for application to a specific program, project, or system shall be formally documented as part of program or project requirements and approved by the responsible ISO and Authorizing Official (AO).


////
APPLICABLE DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  
  List documents in alphanumeric order based on their Document Number or Descriptor.

  Use YOURLS to link to documents and link the Document Number or Descriptor.
////

== Applicable Documents

=== General

The documents listed in this section were used as references during the creation of this Standard. These documents can serve as additional support for users in meeting the requirements of this Technical Standard . 


=== Government Documents

[%header, cols=2*a]
|===
|Document Number|Document Title

|===

// NOTE: Comment out the Non-Government Documents table if you do not have any documents to include.  (i.e., Do not leave a blank table in the document)

=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Number|Document Title
|===

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  Add and remove acronyms as needed. 
  List acronyms, abbreviations, and definitions in alphabetical order.

  Change the title of this section as necessary: 
    If you don't have anything for the Definitions table, delete the table and change Section 3 title to: == Acronyms and Abbreviations
////

== Acronyms, Abbreviations, and Definitions

.Acronyms and Abbreviations
[width="100%",cols="1,3"]
|====
|AO|Authorizing Official
// |ACL|Assessed and Cleared List for technology procurement
|ASCS|Agency Security Configuration Standards
// |CDM|Continuous Diagnostics and Mitigation
|CIO|Chief Information Officer
|CIS|Center for Internet Security
|CSET|Cybersecurity Standards and Engineering Team
// |DAR|Data At Rest
// |DISA|Defense Information Systems Agency
|FFRDC|Federally Funded Research and Development Center
|FISMA|Federal Information Security Modernization Act
//|FPKI|Federal Public Key Infrastructure
|GRC|Glenn Research Center
// |ICAM|Identity, Credential, and Access Management
// |IDI|ICAM Device Integration
|ISO|Information System Owner
|JPL|Jet Propulsion Laboratory
|NASA|National Aeronautics and Space Administration
// |NCTR|NASA Client Trust Reference
// |NIST|National Institute of Standards and Technology
|NPR|NASA Procedural Requirement
// |NSA|National Security Agency
// |NTAM|NASA Trust Anchor Management
|NTSP|NASA Technical Standards Panel
|OCIO|Office of the Chief Information Officer
// |PIV|Personal Identity Verification
// |PKI|Public Key Infrastructure
// |RISCS|Risk Information and Security Compliance System
|SAISO|Senior Agency Information Security Officer
// |SOC|Security Operations Center
// |SSP|System Security Plan
// |STIG|Security Technical Implementation Guide

|====


// If you don't have anything for the Definitions table, delete the table and change Section 3 title to: == Acronyms and Abbreviations

.Definitions
[width="100%",cols="1,3"]
|====
| |

|====


////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4.
////

== DOCUMENT BODY WHICH STARTS AT SECTION 4

Content


////
APPENDIX SECTION
  Appendices are identified differently then the rest of the document, so make sure to use 3 or more markers on subsection titles (=== SUBSECTION). 
  
  If you drop to 2 markers (==) it will start normal numbering again.

  Content of the appendix will format for sections and subsections, but not number them.
  
  It is appropriate to continue using heading tags (===) as normal.
  
  Appendices will be lettered based on the [appendix] tag, so the example title will appear as: 
     APPENDIX A: TITLE OF APPENDIX

  Additional appendices can be used by the [appendix] tag immediately followed on the next line with a 2 marker title (== APPENDIX TITLE).
  
  Subsequent appendices will use appropriate letters (B, C, D...)
////

[appendix]
== TITLE OF APPENDIX
