:doctype: book
ifdef::backend-pdf[]
:front-cover-image: image::build/std-pdf-cover.pdf[]
endif::[]
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
ifdef::backend-html5[]
:toc: macro
:toc-placement!:
endif::[]
:toc-title: TABLE OF CONTENTS
:toclevels: 3
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

// NOTE: include statement need blank line before and after

include::std-document-variables.adoc[]

// **VARIABLES!** 
// AUTO-NUMBERING: Special variables for auto number requirements
// VARIABLE: reqkey = enter the document number (example: 2601) 
//           the counter will auto-increment the requirements so the result will be: reqkey followed by "-R" followed by the requirement number (example: 2601-R8). 
:reqkey: 
:counter: requirement: 0

:noheader:
:nofooter:

ifdef::backend-pdf[]
= NASA STANDARD {document-identifier}
{document-subtitle}
:toc: preamble
endif::[]

ifdef::backend-html5[]
= NASA STANDARD {document-identifier}

// NOTE: include statement need blank line before and after

include::document_basecamp/title_page.adoc[]

toc::[]

endif::[]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row! 
  Oldest/first version in the bottom row!

  You must *add a row to the top of the table* each time a new version of the Standard is published.
 
  Track drafts and include descriptions for each draft while the document is out for review. 

  But be sure to DELETE DRAFT TRACKING and update the approved date when it is signed and ready to be published. 

  The description box must not be left blank, but it should be brief. 
   Example descriptions: "Updated to be applicable to xyz"

   NOTE: 
    Approval Date: this will automatically be pulled from the document-variables.adoc file.

    If you are writing an updated version of a Standard, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log
ifdef::backend-pdf[]
:!nofooter:
:!noheader:
endif::[]

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Approval Date
|Description

|1.0
|{approved-date}
|
|====

<<<

////
Forward:
 Authors need to be sure to insert text to complete the statement in the third paragraph of the Foreword. 
////

== Foreword

This NASA Technical Standard is published by the National Aeronautics and Space Administration (NASA) to provide uniform engineering and technical requirements for processes, procedures, practices, and methods that have been endorsed as standard for NASA programs and projects, including requirements for selection, application, and design criteria of an item.

This NASA Technical Standard is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other Agency documents. This Standard also applies to the Jet Propulsion Laboratory (JPL) (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.


This NASA Technical Standard establishes *(COMPLETE THIS SENTENCE WITH A STATEMENT OF PURPOSE FOR THIS STANDARD)*.

Requests for information, corrections, or additions to this Standard can be made via the "Contact ASCS" form, found here: https://cset.nasa.gov/ascs/requests/.


+++<br><br><br><br>+++


{signatory} +
{signatory-title}

+++<br>+++

////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.

  Please be sure to read comment blocks for instructions. 
////

:numbered:

== Scope

////
Purpose:
  Make sure to complete the sentence AND provide more supporting details (if necessary) to describe why this Standard is necessary.

  This section should include more details and explanation as to why this standard has been created than the simple purpose statement in the Foreword. 
////

=== Purpose

The purpose of this NASA Technical Standard is to establish *(COMPLETE THIS SECTION BY EXPLAINING THE PURPOSE OF THIS STANDARD)*.

// for standards, "establish" is probably the best verb. 
// don't use "provide guidance" - that is handbook verbiage

=== Applicability

This NASA Technical Standard is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other Agency documents. This Standard also applies to JPL (an FFRDC), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

Verifiable requirement statements are numbered and designated by the acronym **26XX-R#**. Verifiable requirement statements also contain the word "*_SHALL_*". This NASA Technical Standard contains *# FILL IN THE TOTAL NUMBER OF SHALL STATEMENTS HERE!* requirements. To facilitate requirements selection by NASA programs and projects, a Requirements Compliance Matrix is provided in Appendix A.  

// numbering of *_SHALL_* statements begins in Section 4 - where the actual content of the Standard begins. do not number the SHALL statement in the applicability section. 

// requirements statements have one (and only one) *_SHALL_* or *_SHALL NOT_* and each one is counted as a single requirement statement. 
// once you have finished writing this Standard, look at the preview to see how many SHALL statements (requirements) it contains. 
// you have to MANUALLY TYPE the number into the sentence above - delete the note in bold and replace with the number
// note: spell out numbers zero - nine. 10 and higher do not need to be spelled out. 
=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at: https://standards.nasa.gov/


=== Tailoring

Tailoring of this NASA Technical Standard for application to a specific program, project, or system *_SHALL_* be formally documented as part of program or project requirements and approved by the responsible Information System Owner (ISO) and Authorizing Official (AO).


////
APPLICABLE DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  
  List documents in alphanumeric order based on their Document Number or Descriptor.

  Use YOURLS to link to documents and link the Document Number or Descriptor.
////

== Applicable Documents

The documents listed in this section contain provisions that constitute requirements of this NASA Technical Standard as cited in the text. These documents can serve as additional support in meeting the requirements of this NASA Technical Standard.

NOTE: A suffix of __x__ on a document identifier indicates that the latest issuance of the document applies.

=== Government Documents

// NOTE: make sure to comment block out any of the tables below if not needed

.White House Releases
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===

.NASA Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===

.NIST Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===

.Other Government Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===

// NOTE: Comment out the Non-Government Documents table if you do not have any documents to include.  (i.e., Do not leave a blank table in the document)

=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Identifier|Document Title
|===

////
ACRONYMS, ABBREVIATIONS, AND DEFINITIONS
  Add and remove acronyms as needed. 
  List acronyms, abbreviations, and definitions in alphabetical order.

  Change the title of this section as necessary: 
    If you don't have anything for the Definitions table, delete the table and change Section 3 title to: == Acronyms and Abbreviations
////

== Acronyms, Abbreviations, and Definitions

include::std_acronymlist.adoc[]

// If you don't have anything for the Definitions table, delete the table and change Section 3 title to: == Acronyms and Abbreviations

.Definitions
[width="100%",cols="1,3"]
|====
| |

|====



////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4.
////

== DOCUMENT BODY WHICH STARTS AT SECTION 4

////
AUTONUMBERING:
  When writing content for a requirement, use the key as follows. 

*({reqkey}-R{counter:requirement})* Then your requirement text following on a single line
                                   ^ make sure you leave a space here!

EXAMPLE: 
 *({reqkey}-R{counter:requirement})* A Windows virtual machine (VM) *_SHALL_* be encrypted using Virtual Trusted Platform Modules (vTPM).
////


 

////
APPENDIX SECTION
  Appendices are identified differently then the rest of the document, so make sure to use 3 or more markers on subsection titles (=== SUBSECTION). 
  If you drop to 2 markers (==) it will start normal numbering again.
  Content of the appendix will format for sections and subsections, but not number them.
  It is appropriate to continue using heading tags (===) as normal.
  Appendices will be lettered based on the [appendix] tag, so the example title will appear as: 
     APPENDIX A: TITLE OF APPENDIX
  Additional appendices can be used by the [appendix] tag immediately followed on the next line with a 2 marker title (== APPENDIX TITLE).
  Subsequent appendices will use appropriate letters (B, C, D...)
////

[appendix]
== Requirements Compliance Matrix

// AUTONUMBERING: This include is generated by the build_req_table.py script
include::std-compliance-matrix.adoc[]

