:doctype: book
ifdef::backend-pdf[]
:front-cover-image: image::build/std-pdf-cover.pdf[]
endif::[]
// Document Setup
:pdf-fontsdir: document_basecamp/fonts/
:pdf-stylesdir: document_basecamp/
:stylesdir: document_basecamp/
:pdf-style: asciidoctor-pdf.yml
:stylesheet: asciidoctor.css
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
// Table of Contents
ifdef::backend-html5[]
:toc: macro
:toc-placement!:
endif::[]
:toc-title: TABLE OF CONTENTS
:toclevels: 3
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

// NOTE: include statement need blank line before and after

include::std-document-variables.adoc[]

////
 **VARIABLES!** 
  The two variables below are special variables for automatically generating numbers to identify the requirements (SHALL statements) in this Standard

  reqkey = enter the document number 
           example: 2601
  
  counter = requirement: 0 (do not change from template) 
  
  The counter will auto-increment the requirements so the result will be: reqkey followed by "-R" followed by the requirement number 
    It will look like this:  2601-R8
////

//VARIABLES: 
:reqkey: 
:counter: requirement: 0

:noheader:
:nofooter:

ifdef::backend-pdf[]
= NASA STANDARD {document-identifier}
{document-subtitle}
:toc: preamble
endif::[]

ifdef::backend-html5[]
= NASA STANDARD {document-identifier}

// NOTE: include statement need blank line before and after

include::document_basecamp/title_page.adoc[]

toc::[]

endif::[]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row! 
  Oldest/first version in the bottom row!

  You must *add a row to the top of the table* each time a new version of the Standard is published.
 
  Track drafts and include descriptions for each draft while the document is out for review. 

  But be sure to DELETE DRAFT TRACKING and update the approved date when it is signed and ready to be published. 

  The description box must not be left blank, but it should be brief. 
   Example descriptions: "Updated to be applicable to xyz"

   NOTE: 
    Approval Date: this will automatically be pulled from the document-variables.adoc file.

    If you are writing an updated version of a Standard, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log
ifdef::backend-pdf[]
:!nofooter:
:!noheader:
endif::[]

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Date Approved
|Description

|1.0
|{approved-date}
|
|====

<<<

////
Forward:
 Authors need to be sure to insert text to complete the statement in the third paragraph of the Foreword. 
////

== Foreword

This NASA Technical Standard is published by the National Aeronautics and Space Administration (NASA) to provide uniform engineering and technical requirements for processes, procedures, practices, and methods that have been endorsed as standard for NASA programs and projects, including requirements for selection, application, and design criteria of an item.

This NASA Technical Standard is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other Agency documents. This Standard also applies to the Jet Propulsion Laboratory (JPL) (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

This NASA Technical Standard establishes *(COMPLETE THIS SENTENCE WITH A STATEMENT OF PURPOSE FOR THIS STANDARD)*.

Requests for information, corrections, or additions to this Standard can be made via the "Contact ASCS" form, found here: https://cset.nasa.gov/ascs/requests/.

+++<br><br><br><br>+++
{signatory} +
{signatory-title}
+++<br>+++



////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.

  Please be sure to read comment blocks for instructions. 
////

:numbered:

== Scope

////
Purpose:
  Make sure to complete the sentence AND provide more supporting details (if necessary) to describe why this Standard is necessary.

  This section should include more details and explanation as to why this standard has been created than the simple purpose statement in the Foreword. 
////

=== Purpose

The purpose of this NASA Technical Standard is to establish *(COMPLETE THIS SECTION BY EXPLAINING THE PURPOSE OF THIS STANDARD)*.

// for standards, "establish" is probably the best verb. 
// don't use "provide guidance" - that is handbook verbiage

=== Applicability

This NASA Technical Standard is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other Agency documents. This Standard also applies to JPL, other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

// Replace the question marks in the line below with your Standard's number! (e.g., 2601)

Verifiable requirement statements are numbered and designated by the acronym **26??-R#**. Verifiable requirement statements also contain the word "*_SHALL_*" or the words "*_SHALL NOT_*". This NASA Technical Standard contains *# FILL IN THE TOTAL NUMBER OF SHALL STATEMENTS HERE!* requirements. To facilitate requirements selection by NASA programs and projects, a Requirements Compliance Matrix is provided in Appendix A.  

// Note: numbering of *_SHALL_* statements begins in Section 4 - where the actual content of the Standard begins. do not number the SHALL statement in the applicability section. 

// IMPORTANT: requirements statements have one (and only one) *_SHALL_* or *_SHALL NOT_*, and each one is counted as a single requirement statement. 

// IMPORTANT: once you have finished writing this Standard, look at the preview to see how many SHALL statements (requirements) this Standard contains and MANUALLY TYPE the number into line 171 above - delete the note in bold and replace with the number.

// note: spell out numbers zero - nine. 10 and higher do not need to be spelled out. 

=== Authority

The Agency Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to Agency cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within the Agency. NTSP provides access to all technical standards at: https://standards.nasa.gov/

In accordance with NPR 2810.1__x__, _Security of Information and Information Systems_, requirement 3.4.2.2, Information System Owner (ISOs) *_SHALL_* implement the requirements and settings defined in all applicable standards and specifications established by ASCS. 

=== Tailoring

Any and all risk-based decisions (RBDs) to tailor this NASA Technical Specification in order to meet the needs of a specific program, project, or system *_SHALL_* be approved by the responsible ISO and Authorizing Official (AO) and formally documented by the ISO or system administrators in the System Security Plan (SSP) under program or project requirements. 

The AO *_SHALL_* ensure that only systems posing an acceptable level of risk to Agency assets, data, and personnel are approved for production operation and that the ISO *_SHALL_* ensure all necessary documentation is produced and maintained. 


////
APPLICABLE DOCUMENTS
  Add Government and Non-Government documents related to this handbook in this section.
  
  List documents in alphanumeric order based on their Document Number or Descriptor.

  Use YOURLS to link to documents and link the Document Number or Descriptor.
////

== Applicable Documents

The documents listed in this section contain provisions that constitute requirements of this NASA Technical Standard. These documents can serve as additional support in meeting the requirements of this NASA Technical Standard.

NOTE: A suffix of __x__ on a document identifier indicates that the latest issuance of the document applies.

=== Government Documents

// NOTE: based on your document's specific needs, make visible any of the document tables that are commented out below: 

////
.White House Releases
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////



.NASA Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
|link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1__x__]| _Security of Information Technology_
// | | 
|===


////
.NIST Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////

////
.Other Government Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////
=== Non-Government Documents

// Example: |CIS Apple iOS 12 Benchmark|Apple iOS 12 Security Benchmark

[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////

+++<br>+++



== Acronyms, Abbreviations, and Definitions

include::acronym_list.adoc[]


// If you don't have anything for the Definitions table, change section title to: == Acronyms and Abbreviations

////
.Definitions

include::definitions.adoc[]

|====
////



////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4.
////

== DOCUMENT BODY WHICH STARTS AT SECTION 4

////
AUTONUMBERING:
  When writing content for a requirement, use the key as follows. 

*({reqkey}-R{counter:requirement})* Then your requirement text following on a single line
                                   ^ make sure you leave a space here!

EXAMPLE: 
 *({reqkey}-R{counter:requirement})* A Windows virtual machine (VM) *_SHALL_* be encrypted using Virtual Trusted Platform Modules (vTPM).
////


 

////
APPENDIX SECTION
  Appendices are identified differently then the rest of the document, so make sure to use 3 or more markers on subsection titles (=== SUBSECTION). 
  If you drop to 2 markers (==) it will start normal numbering again.
  Content of the appendix will format for sections and subsections, but not number them.
  It is appropriate to continue using heading tags (===) as normal.
  Appendices will be lettered based on the [appendix] tag, so the example title will appear as: 
     APPENDIX A: TITLE OF APPENDIX
  Additional appendices can be used by the [appendix] tag immediately followed on the next line with a 2 marker title (== APPENDIX TITLE).
  Subsequent appendices will use appropriate letters (B, C, D...)
////

[appendix]
== Requirements Compliance Matrix

// AUTONUMBERING: This include is generated by the build_req_table.py script
include::std-compliance-matrix.adoc[]

