:doctype: book
// Document Setup
// HTML
:stylesdir: document_basecamp/
//:stylesheet: asciidoctor-draft.css
:stylesheet: asciidoctor.css
// PDF
:pdf-fontsdir: document_basecamp/fonts/
:pdf-themesdir: document_basecamp/
//:pdf-theme: asciidoctor-pdf-draft.yml
:pdf-theme: asciidoctor-pdf.yml
:notitle:
:numbered!:
:data-uri:
:allow-uri-read:
:icons: font
:chapter-label:
:chapter-signifier:
// Table of Contents
:toc: macro
:toc-placement!:
:toc-title: TABLE OF CONTENTS
:toclevels: 3
// xrefstyle full shows the section number and title
:xrefstyle: full
// expand levels of header numbers to 5
:sectnumlevels: 5
:sectanchors:

// Title Page Variables
:document-type: NASA TECHNICAL STANDARD
:document-identifier: NASA-STD-XXXX
// document-title:  USE ALL CAPS. If using acronyms in title, check with Sean for approval. 
:document-title: DOCUMENT TITLE
:document-subtitle: NASA TECHNICAL STANDARD
////
approved-date: 
 Input the approved date only when publishing.             
 Leave blank until then.  
 Date format: year-month-date: 20XX-XX-XX
////
:approved-date:
// document-version: e.g., v1.0,  v1.1, v2.0 etc.
:document-version: vx.x
// is-draft: Is this document a draft? (enter True if it is a draft)
:is-draft: True
// document-stage: Input either  "Draft", "Informal Draft", or "Formal Draft"
:draft-stage: Draft
// revision-date: remove "//" from line below and input revision date if needed
// :revision-date: 20XX-XX-XX
// delete values for the cover-page-marks and leave blank before publishing - do not comment out or build script will break
:cover-page-mark-1: This official draft has not been approved and is subject to modification
:cover-page-mark-2: DO NOT USE PRIOR TO APPROVAL
// superseding-document: leave commented out if N/A, remove "//" on lines below and input doc number if needed
// :superseding-document: NASA-STD-2XXX
// :superseding-document-version: vx.x
:signatory: Michael Witt
:signatory-title: Senior Agency Information Security Officer (SAISO)

// Customize document header
ifeval::["{is-draft}" == "True"]
:document-header: {document-identifier} {document-version} {draft-stage}
endif::[]
ifeval::["{is-draft}" != "True"]
:document-header: {document-identifier} {document-version}
endif::[]

////
 **VARIABLES!** 
  The two variables below are special variables for automatically generating numbers to identify the requirements (*_SHALL_* statements) in this Standard

  reqkey = enter the document number 
           example: 2601
  
  counter = requirement: 0 (do not change from template) 
  
  The counter will auto-increment the requirements so the result will be: reqkey followed by "-R" followed by the requirement number 
    It will look like this:  2601-R8
////

//VARIABLES: 
:reqkey: 
:counter: requirement: 0

:noheader:
:nofooter:

= NASA STANDARD {document-identifier}

// NOTE: include statement need blank line before and after

include::document_basecamp/title_page.adoc[]

toc::[]

////
DOCUMENT HISTORY LOG:
  Newest version in the top row! 
  Oldest/first version in the bottom row!

  You must *add a row to the top of the table* each time a new version of the Standard is published.

  The description box must not be left blank, but it should be brief. 
   Example description: "Updated to be applicable to xyz"
   v1.0 description must be "Initial Release".

    Approval Date: this will automatically be pulled from the document-variables.adoc file.

    If you are writing an updated version of a Standard, the approval date must be hard coded for the earlier version(s), and the Approval Date variable must be used only for the most recent version.
////

[dedication]
== Document History Log

[%header,width="100%",cols="1,1,2"]
|====
|Document Version
|Date Approved
|Description

|
|{approved-date}
|Initial Release
|====

<<<


== Foreword

This NASA Technical Standard is published by the National Aeronautics and Space Administration (NASA) to provide uniform engineering and technical requirements for processes, procedures, practices, and methods that have been endorsed as standard for NASA programs and projects, including requirements for selection, application, and design criteria of an item.

This NASA Technical Standard is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other NASA documents. This Standard also applies to the Jet Propulsion Laboratory (JPL) (a Federally Funded Research and Development Center (FFRDC)), other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

Requests for information, corrections, and/or additions to this Standard can be made via the link:https://cset.nasa.gov/latest/contact-ascs[Contact ASCS] form.

+++<br><br><br><br>+++

ifeval::["{is-draft}" != "True"]
{signatory} +
{signatory-title}

+++<br>+++
endif::[]


////
NUMBERED SECTIONS:
  This is the point at which document numbering begins.

  Please be sure to read comment blocks for instructions. 
////

:numbered:

== Scope

////
Purpose:
  Make sure to complete the sentence AND provide more supporting details (if necessary) to describe why this Standard is necessary.

  This section should include more details and explanation as to why this standard has been created than the simple purpose statement in the Foreword. 
////

=== Purpose

The purpose of this NASA Technical Standard is to establish *(COMPLETE THIS SECTION BY EXPLAINING THE PURPOSE OF THIS STANDARD)*.

// for standards, "establish" is probably the best verb. 
// don't use "provide guidance" - that is handbook verbiage

=== Applicability

This NASA Technical Standard is approved for use by NASA Headquarters and NASA Centers and Facilities, and applicable technical requirements may be cited in contract, program, and other NASA documents. This Standard also applies to JPL, other contractors, recipients of grants and cooperative agreements, and parties to other agreements only to the extent specified or referenced in applicable contracts, grants, or agreements.

// Replace the question marks in the line below with your Standard's number! (e.g., 2601)

Verifiable requirement statements are numbered and designated by the acronym **26??-R#**. Verifiable requirement statements also contain the word "*_SHALL_*" or the words "*_SHALL NOT_*". This NASA Technical Standard contains *# FILL IN THE TOTAL NUMBER OF SHALL STATEMENTS HERE!* requirements. <<Requirements Compliance Matrix>> is provided to facilitate requirements selection by NASA programs and projects.  

////
 Numbering of *_SHALL_* statements begins in Section 4 - where the actual content of the Standard begins. 

 Do not number the *_SHALL_* statement in the applicability section. 

 Requirements statements have one (and only one) *_SHALL_* or *_SHALL NOT_*, and each one is counted as a single requirement statement. 

 Once you have finished writing this Standard, look at the preview to see how many *_SHALL_* statements (requirements) this Standard contains and MANUALLY TYPE the number into the text in the Applicability section - delete the placeholder text and replace with the number.

 Spell out numbers zero - nine. 10 and higher do not need to be spelled out. 
////

=== Tailoring

NASA Technical Standards may contain requirements which are derived from federally mandated critical controls.

Requirements derived from a federally mandated critical control *_SHALL NOT_* be tailored out of a NASA System Security Plan (SSP) for any reason. In the case that a specific program, project, or system is unable to fully meet a requirement that is derived from a federally mandated critical control, a risk-based decision (RBD) addressing this need *_SHALL_*  be approved by the Agency Chief Information Officer (CIO) or designee and the RBD *_SHALL_*  be formally documented in the system's SSP.

Tailoring any requirement which is not derived from a federally mandated critical control in order to meet the needs of a specific program, project, or system *_SHALL_*  be approved by the responsible Information System Owner (ISO) and Authorizing Official (AO) and formally documented by the ISO or designee in the SSP. The AO *_SHALL_*  ensure that only systems posing an acceptable level of risk (LOR) to NASA assets, data, and personnel are approved for production operation and the ISO *_SHALL_* ensure all necessary documentation is produced and maintained.

<<<<
  
=== Authority

The NASA Chief Information Officer (CIO) and Senior Agency Information Security Officer (SAISO) have authorized the Cybersecurity Standards and Engineering Team (CSET) via the Agency Security Configuration Standards (ASCS) initiative to create binding Technical Standards related to cybersecurity topics.

The NASA Technical Standards Program (NTSP), sponsored by the Office of the NASA Chief Engineer, recognizes CSET as a standards-developing organization within NASA. CSET's published ASCS Technical Standards are also listed on the link:https://cset.nasa.gov/latest/nts[NASA Technical Standards] page under Technical Discipline 2000 - Computer Systems, Software, Information Systems. 

In accordance with link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1__x__], _Security of Information and Information Systems_, ISOs *_SHALL_* implement the requirements and settings defined in all applicable standards and specifications established by ASCS. 


////
APPLICABLE DOCUMENTS
  Add Government and Non-Government documents related to this Standard in this section.
  
  List documents in alphanumeric order based on their Document Identifier.

  Use YOURLS to link to documents and link the Document Identifier.
////

== Applicable Documents

=== Requirements Documents

The documents listed in this section contain provisions that constitute requirements of this NASA Technical Standard. These documents can serve as additional support in meeting the requirements of this NASA Technical Standard.

NOTE: A suffix of __x__ on a document identifier indicates that the latest issuance of the document applies.

==== Government Documents

// NOTE: based on your document's specific needs, make visible any of the document tables that are commented out below: 

////
.White House Releases
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


.National Aeronautics and Space Administration (NASA) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title

|link:https://cset.nasa.gov/latest/npr-2810.1[NPR 2810.1__x__]| _Security of Information and Information Systems_

|link:https://cset.nasa.gov/latest/npr-2841.1[NPR 2841.1__x__]|_Identity, Credential, and Access Management_
// | | 
|===


////
.Defense Information Systems Agency (DISA) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////
.National Institute of Standards and Technology (NIST) Documents
[%header, cols=2*a]
|===
|Document Identifier|Document Title
| | 
|===
////


////

// Create YOURLS for any other government documents. Link the title of the source in the table below. 

.Other Government Documents
[%header]
|===
|Document Title
| 
|===
////

////
==== Non-Government Documents

// Create YOURLS for any non-government documents. Link the title of the source in the table below. 

[%header]
|===
|Document Title
| 
|===
////




////
SUPPLEMENTAL GUIDANCE: 
Add any websites, handbooks, etc. that you used as a reference while writing this Standard.
 - List documents in alphabetical order based on the title.
 - *Use YOURLS* to link to documents and *link the title of the document*.
////

////
=== Supplemental Guidance

The resources listed in this section were used as a reference while writing this NASA Technical Standard and may serve as additional support in implementing the requirements defined in this Standard.

[%header]
|===
|Title
| 
|
|===
////


+++<br>+++

// NOTE: If you don't need the Definitions table, change section title to: == Acronyms and Abbreviations

== Acronyms, Abbreviations, and Definitions

include::acronym_list.adoc[]


<<<

include::definitions.adoc[]

<<<



////
DOCUMENT CONTENT
  At this point the body of the document starts.
  Numbering should be at section 4.
////

== DOCUMENT BODY WHICH STARTS AT SECTION 4

////
AUTONUMBERING:
  When writing content for a requirement, use the key as follows. 

*({reqkey}-R{counter:requirement})* Then your requirement text following on a single line
                                   ^ make sure you leave a space here!

EXAMPLE: 
 *({reqkey}-R{counter:requirement})* Information System Owners (ISOs) *_SHALL_* ensure that all operating systems and applications under their authority comply with 100% of the required configuration settings defined in the corresponding NASA-SPEC-2601._x_ and NASA-SPEC-2661._x_ specifications.
////


 

////
APPENDIX SECTION

Appendices will be lettered (not numbered).

ALL ASCS Standards must include an appendix to house the requirements compliance matrix. 

Appendix A of all ASCS Standards *_SHALL_* be titled "Requirements Compliance Matrix".

Following Appendix A: Requirements Compliance Matrix, additional appendices can be added by putting the marker [appendix] on one line, and then, directly underneath (on the next line), write the 2 marker title in all caps for the appendix.
  Example: 
    [appendix]
    == Title of Appendix 

  Example title will appear as:
   APPENDIX B: Title of Appendix 
////

[appendix]
== Requirements Compliance Matrix

// AUTONUMBERING: This include is generated by the build_req_table.py script
include::std-compliance-matrix.adoc[]

